### ISSUE TITLE
Bad performance for big library

### ISSUE THREAD

**Issue by rtrompier** [jvandemo/generator-angular2-library#102]
Hi guys, 

We are trying to improve the performance of our Anuglar 2 components library  : https://github.com/DSI-HUG/dejajs-components

Currently, we push the full library on NPM (with all source files).
We would like to use your generator to push only a bundle.

We have added all our components, and a demo (with angular cli),
If we try to load one of our component in the demo (from dist folder) the build and the rebuild are very slow (more than 10s).

Do you have an idea to make it faster ? 
Thanks ;)

**Comment by jvandemo** [comment]
@rtrompier &mdash; Are you referring to the build of the library or the build of the consuming application? Thanks!

**Comment by rtrompier** [comment]
build of the consuming application

**Comment by jvandemo** [comment]
@rtrompier &mdash; I just cloned your repository and tried it out on my machine.

The initial compilation takes about 20 seconds (when starting `ng serve`). Re-compilations take about 3 seconds (when I make a change to a component or the application).

Are you seeing a different behavior? Thanks!

**Comment by rtrompier** [comment]
Hi jvandemo,
Thanks for your answer.

I think, it was due to our import. Should be fixed now ;) 

Thanks for your help.
Have a nice day.

**Comment by jvandemo** [comment]
@rtrompier &mdash; Thank you for the update, much appreciated! 👍
