### ISSUE TITLE
Error when sass file have Import statement

### ISSUE THREAD

**Issue by rkusuma** [jvandemo/generator-angular2-library#104]
When my component styles (.scss) have `@import` statement.. gulp task `inline-resources` will failed.

```
Error: File to import not found or unreadable: ../stylesheets/styles.scss.
       Parent style sheet: stdin
        on line 1 of stdin
>> @import "../stylesheets/styles.scss";
```

**Comment by rkusuma** [comment]
My workaround is to change from relative path to absolute path
`@import "src/stylesheets/styles.scss"` in `mycomponent.scss`
But i got error in my IDE because the path is not relative.
Can i use relative path for import scss path?

Here is my library structure:
```
src
  -- stylesheets
      -- styles.scss
  -- mycomponent
      -- mycomponent.ts
      -- mycomponent.scss
```

**Comment by paesku** [comment]
have a look at merge request: https://github.com/jvandemo/generator-angular2-library/pull/100

**Comment by jvandemo** [comment]
I just released v10.2.0 with support for .scss imports 👍 

Feel free to re-open if needed. Thanks!

**Comment by rkusuma** [comment]
@jvandemo how can i update my current lib with new version of generator-angular2-library?

**Comment by jvandemo** [comment]
@rkusuma &mdash; From the command line, run

```bash
$ yo
```
and select the option *Update your generators*.

**Comment by lautarobock** [comment]
I had a project created before scss support for compinents. 
What I have to do after upgrade in my project?

**Comment by BenevidesLecontes** [comment]
@jvandemo this feature is broken with the latest version. I can't import sass files anymore. using angular 4.4.6

**Comment by jvandemo** [comment]
@flauc, @deblockt &mdash; Would you be able to have a look at this?

Thanks in advance!
