### ISSUE TITLE
Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by luishmcmoreno** [jvandemo/generator-angular2-library#106]
Hello, I'm facing some problems to build my own library.

I don't know if here is the right place to post this error because I'm almost sure that is my mistake but I'm not sure. 

I created a library with a provider and after I published this library at npm, when I'm importing my library inside a new angular-cli project, i'm facing this library.

I'm importing this library with .forRoot() static method and the library.
 

ERROR in Error encountered resolving symbol values statically. Calling function 'SampleModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /home/luishmcmoreno/Projetos/test3/src/app/app.module.ts, resolving symbol AppModule in /home/luishmcmoreno/Projetos/test3/src/app/app.module.ts

Can someone help me?

**Comment by izifortune** [comment]
Are you linking the library with `npm link` if you are i was having the same issue and I fixed this removing the `node_modules` folders from the library folder

**Comment by jvandemo** [comment]
@luishmcmoreno &mdash; Is it possible to share your code? Thanks!

**Comment by luishmcmoreno** [comment]
Hey, thank you @izifortune but I'm not linking. 

@jvandemo sure!

https://gist.github.com/luishmcmoreno/b968290035770c63b6243c35ba3cb6a8

**Comment by aquintiliano** [comment]
I'm getting the same error, did you solve this?

**Comment by luishmcmoreno** [comment]
Not yet. 

When I run ng serve, the problem happens but if a save some file again (live reload) the problem is gone. But the problem is ng build --prod don't work.

**Comment by aquintiliano** [comment]
are you using that forRoot function? if yes, can you place your code here? I solved the problem here, but I don't know if it is the same case

**Comment by luishmcmoreno** [comment]
Yes I'm using .forRoot() method and I didn't resolved yet. 

The code is here: https://gist.github.com/luishmcmoreno/b968290035770c63b6243c35ba3cb6a8

**Comment by aquintiliano** [comment]
it's not the same case, I was passing a parameter to forRoot function, and it was throwing the error... did you try to verify if everything is fine on the 'dist'?

**Comment by luishmcmoreno** [comment]
I think everything is ok but I'm not sure.

The dist is here: https://www.npmjs.com/package/@pluritech/auth-service

**Comment by mkjsix** [comment]
I think I opened a very similar issue #128

**Comment by ljcp** [comment]
Hi there I'm having the same problem , 

I'm using npm link only for the dist folder , later I'm consuming the library in an Ionic 2 project and everything works fine until i do the --prod in the project , any clue ?  help will be really appreciated

**Comment by ljcp** [comment]
I fixed the issue changing the custom provider , with a export function ! , is a ngc problem and nothing related to this generator ! , thanks !

**Comment by jvandemo** [comment]
@ljcp &mdash; Thank you for sharing your solution, much appreciated. 👍 

@luishmcmoreno &mdash; Can you please verify if that also works for you?

Thanks!

**Comment by luishmcmoreno** [comment]
I didn't understand the solution. But you can label this as solved. I chose another specific way to solve my problem.

Thank you all.

**Comment by jvandemo** [comment]
@luishmcmoreno &mdash; Would you be able to share your solution (if possible)?

It would be great if others can benefit from your solution as well. Thanks!

**Comment by luishmcmoreno** [comment]
Isn't a solution. I didn't using your library in this case.

**Comment by jvandemo** [comment]
@luishmcmoreno &mdash; Ah, ok, thanks for the update! 👍
