### ISSUE TITLE
Secondary package.json

### ISSUE THREAD

**Issue by izifortune** [jvandemo/generator-angular2-library#107]
Hi,

was just reading about the angular package format standards here:
https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#
The secondary `package.json` its not mandatory and looks a little bit different from what we have here.

Just would like to discuss if we really need the secondary one.

**Comment by jvandemo** [comment]
The document you linked to recommends two `package.json` files:

![schermafbeelding 2017-06-04 om 14 36 13](https://cloud.githubusercontent.com/assets/1859381/26761615/439765b4-4933-11e7-8048-f22329ddad7f.png)

If the official guidelines change, we can also update this generator 👍

**Comment by izifortune** [comment]
<img width="694" alt="angular_package_format_-_google_docs" src="https://cloud.githubusercontent.com/assets/3394606/26766100/b2a5c9ee-498a-11e7-8fdd-cdd538c1d454.png">
