### ISSUE TITLE
Cannot find module 'sample-module' when building Angular 4 app made with angular-cli in --prod mode

### ISSUE THREAD

**Issue by robertbrower-technologies** [jvandemo/generator-angular2-library#108]
ng build works. ng serve also works. But when I try to build for production, ie. ng build --prod I get errors:

/web-apps/my-app> ng build --prod
Hash: 173e701e6566e4973f4b                                                              
Time: 28201ms
chunk    {0} polyfills.682313b6b06f69a5089e.bundle.js (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.a9151bb959bc09811ef9.bundle.js (main) 22.1 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.765bef7fc0b73d2d51d7.bundle.js (vendor) 1.1 MB [initial] [rendered]
chunk    {4} inline.4e41d99471f673e3dc5b.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in /web-apps/my-app/src/$$_gendir/node_modules/@mycompany/sample-module/sample-module.ngfactory.ts (10,26): Cannot find module 'sample-module'.

ERROR in /web-apps/my-app/src/$$_gendir/app/app.module.ngfactory.ts (15,26): Cannot find module 'sample-module'.

ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve 'sample-module' in '/web-apps/my-app/src/$$_gendir/app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 23:0-41
 @ ./src/main.ts
 @ multi ./src/main.ts

ng -v:

@ angular/cli: 1.0.4
node: 7.2.0
os: linux x64
@ angular/common: 4.1.3
@ angular/compiler: 4.1.3
@ angular/core: 4.1.3
@ angular/forms: 4.1.3
@ angular/http: 4.1.3
@ angular/platform-browser: 4.1.3
@ angular/platform-browser-dynamic: 4.1.3
@ angular/router: 4.1.3
@ angular/cli: 1.0.4
@ angular/compiler-cli: 4.1.3

Thanks for looking into this. Any info is appreciated.

**Comment by maychan111** [comment]
Did you resolve this issue?  I am running into the same thing.

**Comment by artemsky** [comment]
same here

**Comment by maychan111** [comment]
I posted a workaround that does not use flat module in #116.
