### ISSUE TITLE
Runtime error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by robertbrower-technologies** [jvandemo/generator-angular2-library#111]
I am using angular-cli. I am using this generator and I am very happy with it except that I have a runtime error when I build my app using --prod. I have set all the "dependencies" for @angular/... to "4.1.3" in my app's package.json. I have set all the "devDependencies" for @angular/... to "4.1.3" in my library's package.json and "peerDependencies" for @angular/core to "4.1.3" in src/package.json. But it does not solve the problem. Can anyone offer any help? Thanks.

{Edit} I am using the instructions in the "Consuming your library during development" section to npm link because we do not yet have our own package repo. Could this be the problem?

**Comment by robertbrower-technologies** [comment]
For anyone who might also encounter this problem...

"NgModule from one node_modules does not equal NgModule from another node_modules even if they're the same version"

... and there is the problem.

To solve this...

you need to have a central location for all your app and lib dependencies, for example, a global npm cache.

For each shared dependency, go into the global cache's node_modules/[dependency] folder, node_modules/@angular/core for example, and create an npm link by executing sudo npm link.

Then delete the @angular folder that exists in all of your app and lib node_modules folders and from the node_modules folders execute sudo npm link [dependency], so sudo npm link @angular/core for example, for each dependency.

Rebuild your libs, then rebuild your apps.

**Comment by sgruhier** [comment]
thanks for the solution. I hope we'll get a easier way to solve that soon !

**Comment by jvandemo** [comment]
Thank you for reporting.

See #113 for a solution. Closing this issue but feel free to re-open if needed 👍
