### ISSUE TITLE
Compodoc stopped generate interfaces

### ISSUE THREAD

**Issue by artemsky** [jvandemo/generator-angular2-library#112]
I have two folders with my project, 
1 - generator v**10.0.0**
2 - generator v**10.2.2**

Looks like after updating from 10.0.0 to 10.2.2, it stopped generate interfaces.

From the cli i see that it parse it, but still not generating files.

[Output from version 10.0.0 ](https://artemsky.github.io/ng-snotify/documentation/index.html)
10.2.2 - all the same, but without interfaces.

looks like **compodoc** has the same version in both examples.

Updating compodoc does not solve this problem

**Comment by jvandemo** [comment]
@RSginer &mdash; Would you be able to have a look at this? Thanks in advance!

**Comment by RSginer** [comment]
@jvandemo yes I can, thanks for having me!

**Comment by jvandemo** [comment]
@RSginer &mdash; Awesome, thank you, much appreciated! 👍

**Comment by jvandemo** [comment]
@RSginer &mdash; Have you been able to have a look at this yet? Thanks!

**Comment by artemsky** [comment]
looks like compodoc closed this issue - https://github.com/compodoc/compodoc/issues/198

**Comment by jvandemo** [comment]
@artemsky &mdash; Thank you for your follow-up 👍
