### ISSUE TITLE
Question: How to include an assets folder that contains a stylesheet or images?

### ISSUE THREAD

**Issue by robertbrower-technologies** [jvandemo/generator-angular2-library#118]
What is the prescribed way to include an assets folder with css and images to be included in ./dist?

**Comment by kajnelissen** [comment]
You could just simply copy your assets folder to the `./dist` folder after running `npm run build`. We have these scripts in our `package.json`:

```
"scripts": {
    "build": "gulp build && npm run build:copy",
    "build:copy": "cpx src/assets/**/* dist/assets"
}
```

**Comment by jvandemo** [comment]
@robertbrower-technologies &mdash; You can indeed add your own script as @kajnelissen suggests.

I will close this issue, but feel free to re-open if you need more help or input.

@kajnelissen Thank you for your help, much appreciated! 👍

**Comment by dolanmiu** [comment]
Sorry for bringing up this issue again, but this goes against the advice given below no?

https://github.com/jvandemo/generator-angular2-library/issues/115

Sorry if I missed something obvious
