### ISSUE TITLE
Create process for running unit tests

### ISSUE THREAD

**Issue by raphael-volt** [jvandemo/generator-angular2-library#122]
Hello,
I have wrote a tutorial to setup karma with your sample library. I am not sure that is the best way, but it works. 
You may be inspired to automate the process.
See [ng2-testable-lib](https://github.com/raphael-volt/ng2-testable-lib)

Thank you for your project.

**Comment by jvandemo** [comment]
@raphael-volt &mdash; Thank you for sharing.

I have added a link to your tutorial in the README:
https://github.com/jvandemo/generator-angular2-library#how-can-i-configure-karma

Thanks again, much appreciated! 👍
