### ISSUE TITLE
Tests fails when a demo is included

### ISSUE THREAD

**Issue by MurhafSousli** [jvandemo/generator-angular2-library#125]
I include demo app (generated by angular cli) with the library
This cause the tests to fail, for example I get this when I run the tests.
```
demo/src/app/app.module.ts(5,34): error TS2307: Cannot find module 'ngx-progressbar'.
demo/src/app/main/main.component.ts(2,33): error TS2307: Cannot find module 'ngx-progressbar'.
npm ERR! Test failed.  See above for more details.
```
Is it possible to make the testing task to run for src directory only?

**Comment by jvandemo** [comment]
Currently, the generator does not create a karma configuration yet.

However, you can run `karma init` from the root of your project and manually tweak the settings in `karma.conf.js` so only the tests in `src` are run.

As soon as official guidelines are available for testing, we will also add a karma config to the generator. Thanks!

**Comment by jvandemo** [comment]
PS: Feel free to post your karma config here if you wish to share it with others. Thanks again!
