### ISSUE TITLE
Error encountered resolving symbol values statically. Function calls are not supported. 

### ISSUE THREAD

**Issue by mkjsix** [jvandemo/generator-angular2-library#128]
Hi,

We created a base module with this generator and we want to import it into an Angular4 app, but when we run `ng build` on the importing app, we get this error:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 1212:23 in the original .ts file), resolving symbol GartBaseModule in /Users/mturatti/src/softinstigate/ART/art-web-editor/node_modules/gart-base/dist/index.js, resolving symbol CoreModule in /Users/mturatti/src/softinstigate/ART/art-web-editor/src/core/core.module.ts, resolving symbol CoreModule in /Users/mturatti/src/softinstigate/ART/art-web-editor/src/core/core.module.ts, resolving symbol CoreModule in /Users/mturatti/src/softinstigate/ART/art-web-editor/src/core/core.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/mturatti/src/softinstigate/ART/art-web-editor/src'
 @ ./src/main.ts 6:0-74
 @ multi ./src/main.ts

Do you have any suggestion to investigate further this? Thank you!

**Comment by mkjsix** [comment]
It's was due to an error packaging the dist folder.

**Comment by mkjsix** [comment]
It was due to an error packaging the source library.

**Comment by jvandemo** [comment]
@mkjsix &mdash; Thank you for the update! 👍

**Comment by luishmcmoreno** [comment]
@mkjsix can you tell me what error?

**Comment by mkjsix** [comment]
@luishmcmoreno in our node_modules (of the consuming app) we had the source folder of the library instead of the "dist" sub-folder, now we are installing the "dist" at the root of the library on node_modules.
