### ISSUE TITLE
How to add dependency of other plugin?

### ISSUE THREAD

**Issue by AshwaniChoudhary** [jvandemo/generator-angular2-library#129]
First I want to thanks for creating this generator :+1:  .... now my question  ... my plugin is dependent on other plugin .. Normally it is working fine, I am able to create build, component, services.

Now I add a dependency and it is working fine by linking src folder using `npm link`  ... but when I create build and try to use it by doing ` npm install sample-library` then it is not working.

Angular cli says **Cannot find module ' sample-library'** .. but i can see my lib and its dependency in node module folder.

**Comment by jvandemo** [comment]
Is it possible to share your library code? Thanks!

**Comment by AshwaniChoudhary** [comment]
Thanks Jvandemo, My issues is resolved :smile:. I added my dependencies in both package JSON and created build from src folder and everything is working as expected now ..

**Comment by jvandemo** [comment]
@AshwaniChoudhary &mdash; Fabulous, thank you for the update! 👍
