### ISSUE TITLE
Generator fails on typings install

### ISSUE THREAD

**Issue by fluky** [jvandemo/generator-angular2-library#13]
> typings install

typings ERR! message https://api.typings.org/entries/dt/es6-shim/tags/0.31.2%2B20160317120654 responded with 401, expected it to equal 200

typings ERR! cwd /Users/e041115/dev/ess-ux-components
typings ERR! system Darwin 14.5.0
typings ERR! command "/usr/local/Cellar/node5/5.11.1/bin/node" "/Users/e041115/dev/ess-ux-components/node_modules/.bin/typings" "install"
typings ERR! node -v v5.11.1
typings ERR! typings -v 1.3.0
typings ERR! code EINVALIDSTATUS

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN @angular/core@2.0.0-rc.1 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.1 requires a peer of zone.js@^0.6.6 but none was installed.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node5/5.11.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ess-ux-components@0.1.0 postinstall: `typings install`
npm ERR! Exit status 1

**Comment by jvandemo** [comment]
@fluky &mdash; Strange, I'm getting a 200 OK response here.

Can you consistently reproduce this? What steps have you taken before you get this error?

Thanks!!

**Comment by fluky** [comment]
Yea, I've blown away the directory and retried 3 or 4 times.  I'm just running the generator in a new directory, no other steps.

**Comment by jvandemo** [comment]
@fluky &mdash; I have just released v2.1.0 of this generator with support for Angular 2.0.0-rc.3.

Can you install the latest version and see if that causes the same problem?

I can't reproduce your issue here locally so all input is welcome. Thanks!

**Comment by fluky** [comment]
This version loaded clean.  Thanks.

**Comment by jvandemo** [comment]
@fluky &mdash; Excellent, thanks for the confirmation!
