### ISSUE TITLE
How to include global styles?

### ISSUE THREAD

**Issue by robertbrower-technologies** [jvandemo/generator-angular2-library#130]
I use gridforms, ie. npm install --save gridforms

I want all of the components in my module to use the stylesheet /node_modules/gridforms/gridforms/gridforms.css.

But I do not want to include that stylesheet in the styleUrls array of every component.

How can this be done?

**Comment by izifortune** [comment]
I believe this can be a little bit tricky since you would need to inject the stylesheet only when that module it's required. 

Does angular have support for this?

**Comment by robertbrower-technologies** [comment]
No. There are no module specific stylesheets. But I guess you understand the problem. If I put ../node_modules/gridforms/gridforms/gridforms.css into every one of the components in this angular library that uses it, then I think the library will become quite large. Won't it?

**Comment by izifortune** [comment]
I would defer this to the container of the module ( with either webpack or another more suitable module loader ) 

For the time being but now I'm thinking on how to solve this, not an expert on rollup honestly but I have another idea to try.

**Comment by robertbrower-technologies** [comment]
As a temporary workaround, i deferred it to my app's angular-cli.json styles:[] array. But then I did it the way i described in my last comment which is perfectly fine and exactly what i need. I am not concerned about the extra component required in order to get it.

**Comment by jvandemo** [comment]
@robertbrower-technologies &mdash; I think the component with empty template and `ViewEncapsulation.None` is a clean solution. Thank you for sharing.

I will close this issue. Feel free to re-open if you feel it is needed. Thanks again!
