### ISSUE TITLE
ERROR in Cannot read property 'provide' of undefined

### ISSUE THREAD

**Issue by lucasvieceli** [jvandemo/generator-angular2-library#138]
#I'm using google translator.

I already had a library in the old version, I'm upg
I put all my code in the src folder and executed command "npm run build"rading to the new one.

I went to test in an application and this error is occurring

```
ERROR in Cannot read property 'provide' of undefined
webpack: Failed to compile.

```
github: https://github.com/lucasvieceli/teste

I'm using angular -cli

**Comment by jvandemo** [comment]
@lucasvieceli &mdash; Can you please try:

```
import {SelectService} from './service/select.service';
```

instead of:

```
import {SelectService} from './service';
```

in `src/index.ts` on line 11.

**Comment by desfero** [comment]
Have same error, anyone know what can cause this?

**Comment by lucasvieceli** [comment]
Solved, thank you

**Comment by desfero** [comment]
@jvandemo what is the point of doing this, because when change all my module imports from './service' to './service/<type>' the issue magically disappear. Cannot find any information regarding this behavior

**Comment by Janatbek** [comment]
I think typescript thinks './service' is a file and not a folder that contains a file,  by adding '/' in the path './service/' you are telling that there's a folder called service. 
Without '/' you are basically telling its a service.ts file that typescript removes .ts at the end.

**Comment by kktam** [comment]
It is generally in ES6 import that './service' will assume it is a Angular (or React) or other ES6 Javascript files, and look for './service.js'. So adding a slash on the back remove the confusion.

**Comment by jvandemo** [comment]
@desfero &mdash; In theory both should work. Sometimes importing a barrel can import more than importing a specific service. It's hard to say without seeing actual code to know what is causing issues. Hope that helps!
