### ISSUE TITLE
NPM START 

### ISSUE THREAD

**Issue by chadhumphrey** [jvandemo/generator-angular2-library#14]
I will apologize in advance, (I'm new to node/npm) this is not an issue and more than likely a user error! 

 But really want to run your generator. 

So ran the generator answer the questions... etc. 
But when I go to "npm start" this is what I get. 

> `0 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]

2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /var/www/html/broncos
6 error Linux 4.4.0-31-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error node v4.2.6
9 error npm  v3.5.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]`

For the life of me I can't figure out where the start script is?

**Comment by jvandemo** [comment]
@chadhumphrey &mdash; No need to apoligize Sir!

There is no `start` script defined in `package.json` so that is probably why you are seeing the above.

The following scripts are supported, as you can see in `package.json`:

```javascript
"scripts": {
  "lint": "tslint src/**/*.ts",
  "test": "tsc && karma start",
  "postinstall": "typings install",
  "prepublish": "tsc",
  "tsc": "tsc",
  "typings": "typings"
}
```

So you can run:

```bash
$ npm run lint
$ npm run test
$ npm run tsc
$ npm run typings
```

Does that make sense?

Thanks!

**Comment by chadhumphrey** [comment]
That works Thanks!

**Comment by jvandemo** [comment]
Ok, super, thanks for the confirmation @chadhumphrey!
