### ISSUE TITLE
Improve styleUrls regex

### ISSUE THREAD

**Issue by Ixoh** [jvandemo/generator-angular2-library#140]
Hello,

It's not a "big bug". But it took me one hour to understand why my styleUrls scss file was not inlined.

I had to change from
> styleUrls : ['image-chooser.scss']
to 
> styleUrls: ['image-chooser.scss']

Yes, I just had to remove the space between  'styleUrls' and ':'  

I changed the code in  **gulp/inline-resources.js function inlineStyle**

change regex from : `/styleUrls:\s*`
to`/styleUrls\s*:\s*`

Anyway, thanks for your job, great generator

**Comment by jvandemo** [comment]
@Ixoh &mdash; Fix has been added and released as v11.0.1. Thank you for reporting, much appreciated! 👍
