### ISSUE TITLE
[Question] Setup with GIT

### ISSUE THREAD

**Issue by Ixoh** [jvandemo/generator-angular2-library#141]
Hello,

I'm developping components since few days without problem but now i'm having  problems since I need to import {..} things from my library. 

To share my component with my team i'm using **git** and they can have access to my components with npm by adding this inside package.json.

`"@asi-ngtools/lib" : "git+ssh://git@......./asi-ngtools.git#v0.1.0"`

I have followed the issue #75 
added   `"name": "@asi-ngtools/lib"`    inside `src/package.json`
added   `"flatModuleId": "@asi-ngtools/lib"` inside "angularCompilerOptions" in  `ts.config.es5.json`

here is my build folder "dist" 

![image](https://user-images.githubusercontent.com/10477005/27553514-6efb0592-5aab-11e7-975d-06e01bb2b1dc.png)

This is what I get in  nodes_modules.

![image](https://user-images.githubusercontent.com/10477005/27553547-912654e6-5aab-11e7-9c57-7e7a020b984c.png)

All "normal" component work fine  (component directly used in HTML) but when I try to import  them like this I got compilation error

`import { AsiTable } from '@asi-ngtools/lib`;

`[ts] Module '"c:/workspace/WS/WS_ASI_NGTOOLS/asi-ngtools-test/node_modules/@asi-ngtools/lib/asi-ngtools"' has no exported member 'AsiTable'.`

I got this in   **asi-ngtools.d.ts**

```
export * from './index';
export { AsiTable as ɵf } from './components/asi-table/asi-table.component';
.... (many others)
```

If I use a complete path I got : 

`import { AsiTable } from '@asi-ngtools/lib/components/asi-table/asi-table.component';`

```
ERROR in ./src/app/asi-table-test/asi-table-test.component.ts
Module not found: Error: Can't resolve '@asi-ngtools/lib/components/asi-table/asi-table.component' in 'C:\workspace\WS\WS_ASI_NGTOOLS\asi
-ngtools-test\src\app\asi-table-test'
 @ ./src/app/asi-table-test/asi-table-test.component.ts 10:0-85
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

What i'm doing wrong ?

**Comment by Ixoh** [comment]
Ok, after many hours of search I finally found that I needed to add "export" to be able to use my components / service outside. 

export * from './components/asi-table/asi-table.component';
export * from './components/asi-table/asi-table-data';

Simple solution which make sens but It was not write in the documentation. So I'm doing right ?

**Comment by jvandemo** [comment]
@Ixoh &mdash; Thank you for your update. Yes, you are doing things correctly. When using a barrel (`index.ts`) you must indeed `export` all JavaScript modules that you wish to `import` later from within the consuming application.

I will close this issue but feel free to re-open if you feel it's needed. Thanks! 👍
