### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by theunreal** [jvandemo/generator-angular2-library#142]
I'm trying to figure out how to get unit testing working with a library.
This is what I tried:

`karma init` - generates the following `karma.conf`:

    // Karma configuration
    
    module.exports = function(config) {
      config.set({
    
        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',
    
    
        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],
    
    
        // list of files / patterns to load in the browser
        files: [
          'src/*.ts',
        ],
    
    
        // list of files to exclude
        exclude: [
        ],
    
    
        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
        },
    
    
        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],
    
    
        // web server port
        port: 9876,
    
    
        // enable / disable colors in the output (reporters and logs)
        colors: true,
    
    
        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,
    
    
        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,
    
    
        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['Chrome'],
    
    
        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false,
    
        // Concurrency level
        // how many browser should be started simultaneous
        concurrency: Infinity
      })
    }

Then I wrote the following test file: `library.spec.ts`:

    import { TestBed, async } from '@angular/core/testing';
    
    import { VRViewComponent } from './vrview.component';
    
    describe('VRViewComponent', () => {
        beforeEach(async(() => {
            TestBed.configureTestingModule({
                declarations: [
                    VRViewComponent
                ],
            }).compileComponents();
        }));
    
        it('should create the app', async(() => {
            const fixture = TestBed.createComponent(VRViewComponent);
            const app = fixture.debugElement.componentInstance;
            expect(app).toBeTruthy();
        }));
    });

When I run karma, I get the following error in my editor:

    Empty test suite.
    
    Process finished with exit code 0

Is there anything wrong with my setup?

**Comment by izifortune** [comment]
You can try out jest was added with this pr  #103 which is already setup for unit testing

**Comment by jvandemo** [comment]
@theunreal &mdash; Did you manage to get it to work with Jest?

@izifortune &mdash; Thank you for your help, much appreciated! 👍
