### ISSUE TITLE
'sample-component' is not a known element

### ISSUE THREAD

**Issue by papaiatis** [jvandemo/generator-angular2-library#145]
I followed the installation steps for development and included the `SampleModule` in my main project but when I try to use the `SampleComponent`, I get this angular error in the console:
`'sample-component' is not a known element`

I did not change anything after I generated the library using `yo`, so it should be reproducible.
My main project uses webpack to compile the app, so I also did what mentioned in https://github.com/jvandemo/generator-angular2-library/issues/113#issuecomment-306075531 because without that it did not even found the module.

Any help would be great!

**Comment by kajnelissen** [comment]
Did you put the `SampleComponent` in the `exports` from the library module? Like so:

    @Module({
        exports: [
            SampleComponent
        ]
    })
    export class SampleModule { }

**Comment by jvandemo** [comment]
@papaiatis &mdash; I generated a brand new library and was unable to reproduce this. 

Are you still seeing this error? Thanks!

**Comment by jvandemo** [comment]
@papaiatis &mdash; Ok, great to hear. Thank you for the update! 👍
