### ISSUE TITLE
Template files are not coppied to dist folder

### ISSUE THREAD

**Issue by LunicLynx** [jvandemo/generator-angular2-library#15]
The template files of components are not copied to the dist folder.

It would be possible to create them there directly but this does not seem like a clean solution.

```
@Component({
    moduleId: module.id,
    templateUrl: require('./abc.html'), // <<-----
})
export class AbcComponent implements OnInit {
```

**Comment by jvandemo** [comment]
I think, for now, the best approach is to use inline templates for libraries (see https://github.com/valor-software/ng2-bootstrap/blob/development/components/alert/alert.component.ts for an example).

Because Angular 2 recently started using Webpack, another option may be to use a Webpack build process to generate a bundle for production.

Any other thoughts would be appreciated.

**Comment by jbrecht** [comment]
not the best solution, but I added these scripts in package.json:
```
    "htmlcopy": "copyfiles src/**/*.html dist",
    "lesscopy": "copyfiles src/**/*.less dist",
    "dist": "npm run tsc && npm run htmlcopy && npm run lesscopy",
```

which means you must add this to devDependencies:
`    "copyfiles": "1.0.0"`

**Comment by jvandemo** [comment]
@jbrecht &mdash; Thanks for your input. I will leave this issue open until Angular CLI comes with a recommendation that we can port to this generator.

**Comment by jvandemo** [comment]
As a reference, Angular Material uses Gulp to copy the files over the `dist` directory: https://github.com/angular/material2/blob/master/tools/gulp/tasks/components.ts

**Comment by caroso1222** [comment]
Something cool that material does is to inline html and scss files into the generated js components. This way, you'd only be shipping js. Checkout [this](https://github.com/angular/material2/blob/master/tools/gulp/tasks/components.ts#L115) where the task is initiated, then it calls another gulp task called `:inline-resources` which, after going through a bunch of functions, gets to [this function](https://github.com/angular/material2/blob/master/scripts/release/inline-resources.js#L90). It basically replaces all instances of `templateUrl` with the content of the respective file. Same with `styleUrls` .scss files.

I found [this datepicker library](https://github.com/kekeh/mydatepicker) which does the same. You can check out the gulp file [here](https://github.com/kekeh/mydatepicker/blob/master/gulpfile.js#L47-L61). I pointed out the gulp task which makes the template and style inlining into the component. It's simpler than the material's one to understand, but the idea is the same.

If this makes sense to you, I can go ahead and take a stab at adding this to the generator so we can include it into the build & publish pipeline.

**Comment by jvandemo** [comment]
@caroso1222 &mdash; Indeed, we are currently waiting for recommendations by the Angular team on how we can best approach this. Thank you for sharing your thoughts and offering to help. Much appreciated.

For now, I would suggest to only take action when we know what the official recommendation is.

**Comment by caroso1222** [comment]
Sure, sounds good! Lets wait for the official recommendation then.

**Comment by AhsanAyaz** [comment]
I just published my [library](https://github.com/AhsanAyaz/ng2-hz-datepicker) over npm and found the same issue. Not loading templates . Looks like I'll have to use inline templates for now 😅

**Comment by jvandemo** [comment]
@AhsanAyaz &mdash; Inline templates indeed seem to be the way to go (for now). Thank you for your feedback and trying out the generator.

**Comment by gilbertowa** [comment]
The below has some solutions and comments on how to solve this, I tried to replicate but I could not make it work yet. If anyone wants to try it is here:

https://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html

**Another info**: http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/#checklist

**Comment by tonkla** [comment]
Another solution, use [`html-loader`](https://www.npmjs.com/package/html-loader) (and css/scss loader)
```
@Component({
    selector: 'app-abc',
    template: require('./abc.component.html')
})
export class AbcComponent implements OnInit {
```
webpack.conf.js
```
module: {
  rules: [{
    test: /\.html$/,
    use: [ {
      loader: 'html-loader',
      options: {
        minimize: true,
        removeComments: true,
        collapseWhitespace: true
      }
    }],
  }]
}
```

**Comment by jvandemo** [comment]
@gilbertowa, @tonkla &mdash; Thank you both for the great suggestions! 👍

**Comment by BioPhoton** [comment]
So is there a solution beside inline templates?
Would be cool to have the html in a separate file. :-)

thx Michael

**Comment by caroso1222** [comment]
@BioPhoton what material currently does is to inline CSS and HTML into the component via gulp in build step. ngconf just announced they will be releasing a guideline on how to properly build ng libraries, so I guess we'll be able to address a lot of issues when this comes out.

**Comment by jvandemo** [comment]
There is an experimental branch with Gulp that should support Mac, Linux and Windows (see #65).

Can any of you please install the Gulp version:

```bash
$ npm install -g https://github.com/jvandemo/generator-angular2-library#feat/gulp
```

After generating a library, you should be able to build your library using:

```
$ npm run build
```

or use watch mode to build whenever a file changes in `src`:


```
$ npm run build:watch
```

Templates and styles should now be inlined automatically in the resulting bundle in the `dist` directory.

Can anyone please verify if everything works as expected on your machine?

Thanks in advance!

**Comment by jvandemo** [comment]
v9.0.0 has been released with automatic inlining of HTML and CSS files.

Feel free to report issues if you experience problems. Thanks!

**Comment by abalad** [comment]
@jvandemo It seems that it happened again in the latest versions: 

https://github.com/jvandemo/generator-angular2-library/issues/199

**Comment by tonysamperi** [comment]
Quote @abalad
