### ISSUE TITLE
Feature request: Include demo project in generator

### ISSUE THREAD

**Issue by edriang** [jvandemo/generator-angular2-library#152]
Hi, I think that the possibility to have a demo project on the generated project could be very useful.

Currently, I'm managing to solve this in the following way:
- executed yo angular2-library (e.g project name `my-lib`)
- run `ng new demo` from the root path (I'm doing this at the root in order to avoid the contents being compiled by the lib build task)
- added `demo/*` to ignore list in `/.npmignore` (don't know if necessary)
- configured a npm start script in root package.json to: `start: cd demo && ng serve`
- `npm run build`
- cd `my-lib/dist` and ran `npm link`
- cd to `demo/node_modules` and run `npm link my-lib`
- referenced `my-lib` on the `demo` project (e.g. import { MiLibModule } from 'mi-lib'
- `npm start` to serve demo project
- in another terminal opened the project path and run `npm run build:watch`

Everything is working as expected:
- I have a demo project referencing the lib (with auto watch)
- Can work on the lib and see the results on the demo project

I think that it could be very helpful to everyone to automate this steps. 
Maybe making it optional during project scaffolding or running additional command like `npm run generate-demo`

What do you think? I'm not experienced in node_modules (neither in yeoman), so I'm just sharing my ideas and workaround if you want to improve the generator (awesome btw!)

**Comment by izifortune** [comment]
There are already a couple of this issues floating around https://github.com/jvandemo/generator-angular2-library/issues/131.

And another good one could be to include www.angularplayground.it also as well.

I think we should have one option and a decision/discussion should be made for this

**Comment by edriang** [comment]
Thanks, angularplayground seems interesting! Is anyone working on integrating that? you know if there is any ticket where I can follow it's progress? Thanks

**Comment by izifortune** [comment]
I wonder how we could integrate playground inside the generator

**Comment by edriang** [comment]
I ended up changing the generated project structure, merging it with angular-cli generated code for the demo project, and using the generator-angular2-library gulp script to build the library itself.

You can check out the project from here. I'm currently using this on some libraries I've developed so far:
https://github.com/edriang/ngx-library-template

**Comment by jvandemo** [comment]
@edriang &mdash; Thank you for sharing, much appreciated!

I will close this issue, but feel free to re-open if you need further assistance.
