### ISSUE TITLE
Generating error

### ISSUE THREAD

**Issue by flauc** [jvandemo/generator-angular2-library#153]
Hi @jvandemo 

Thank you for the great library 👍 .
I'm getting a strange error though. When I run `yo angular2-library` I don't get the `tsconfig.es5.json` file in src folder, and because of this (I think) when using the published library  I get this error: 
```
SampleLibraryModule is not an NgModule
```

Any idea why this might be happening? 
Thank you.

**Comment by jvandemo** [comment]
@flauc &mdash; Thank you for your kind words, much appreciated.

Are you using the latest version of the generator?

You can find instructions on how to update the generator here: https://github.com/jvandemo/generator-angular2-library#how-can-i-update-my-generator-to-the-latest-version.

Thanks!

**Comment by flauc** [comment]
I didn't have the latest release, sorry for wasting your time.

**Comment by jvandemo** [comment]
@flauc &mdash; Ok, great, no problem. Thank you for the update! 👍

**Comment by abalad** [comment]
+1I already updated the version and this error continues
