### ISSUE TITLE
How do I specify my library's external dependency?

### ISSUE THREAD

**Issue by sheldonyss** [jvandemo/generator-angular2-library#155]
My library dependent on the angular material. When I consume my library, my app does not install these external dependencies automatically.

I noticed these warnings during library build process.

angular/platform-browser is imported by build\pipes\safe.js, but could not be resolved – treating it as an external dependency
angular/platform-browser/animations is imported by build\index.js, but could not be resolved – treating it as an external dependency
angular/material is imported by build\index.js, but could not be resolved – treating it as an external dependency

**Comment by jvandemo** [comment]
@sheldonyss &mdash; Did you add angular material as a peer dependency? Thanks!

**Comment by chriszrc** [comment]
For npm 3, peerDependencies aren't installed by default anymore:

http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by jvandemo** [comment]
@chriszrc &mdash; You are right. However, it should display an 'Unmet peer dependency" warning to notify that the peer dependency is not installed. Thanks for your input!

**Comment by sgentile** [comment]
I'm also wanting to install a 3rd party library (ie. leaflet) - what are the correct steps - do you install it as npm install leaflet --save  ?   Or you are saying, create a peerDependency section and add it there ?

Along with this - I'm going to be bringing in the leaflet.css dependencies - I had used a scss global and have an @import - how would I add this as well ?

Also, do I need to add anything to the tsconfig.app.json for the host app ?

Thanks!

**Comment by jvandemo** [comment]
@sgentile &mdash; You add leaflet as a peer dependency to your library (by creating a `peerDependency` section in `src/package.json` of your library).

Then it is up to the consuming application to install leaflet (and import the required code and CSS from leaflet).

By adding leaflet as a peer dependency, the consuming application will show a warning when running `npm install` and leaflet is not installed, so that the developer knows that it should be installed.

Does that make sense? Thanks!

**Comment by jvandemo** [comment]
Closed due to lack of response of the initial issue creator. Feel free to re-open if needed. Thanks!

**Comment by jvandemo** [comment]
Quick update: FAQ has been added to the README: https://github.com/jvandemo/generator-angular2-library#what-if-my-library-depends-on-a-third-party-library.

**Comment by sgentile** [comment]
Thank you for your response and update

**Comment by Davy-F** [comment]
I've added peerDependencies to package.json but still getting the "treating it as an external dependency" errors in the command line during build? Any ideas?

**Comment by tomwanzek** [comment]
@Davy-F The "treating it as an external dependency" message is related to RollUp. Have a look at the treatment of `externals`, e. g. [here](https://rollupjs.org/#creating-your-first-bundle). In particular, the `external` configuration option.

**Comment by Davy-F** [comment]
@tomwanzek Thanks. Does the generator builder take into consideration the rollup.config file, because I know it has it's own rollup functionality?

**Comment by tomwanzek** [comment]
@Davy-F Good point, I should have mentioned this outright: The gulp tasks created by the generator allow passing in of RollUp config option. Look for the `rollup:umd` task in `gulpfile.js`. For one of my libraries, I amended the `external` and `globals` entry as shown below. The `external` property will drop the warning message you referenced.

```javascript
/**
 * 6. Run rollup inside the /build folder to generate our UMD module and place the
 *    generated file into the /dist folder
 */
gulp.task('rollup:umd', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
  // transform the files here.
    .pipe(rollup({

      // Bundle's entry point
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#entry
      entry: `${buildFolder}/index.js`,

      // Allow mixing of hypothetical and actual files. "Actual" files can be files
      // accessed by Rollup or produced by plugins further down the chain.
      // This prevents errors like: 'path/file' does not exist in the hypothetical file system
      // when subdirectories are used in the `src` directory.
      allowRealFiles: true,

      // A list of IDs of modules that should remain external to the bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#external
      external: [
        '@angular/core',
        '@angular/common',
        'd3-array',
        'd3-axis',
        'd3-brush',
        'd3-chord',
        'd3-collection',
        'd3-color',
        'd3-contour',
        'd3-dispatch',
        'd3-drag',
        'd3-dsv',
        'd3-ease',
        'd3-force',
        'd3-format',
        'd3-geo',
        'd3-hierarchy',
        'd3-interpolate',
        'd3-path',
        'd3-polygon',
        'd3-quadtree',
        'd3-queue',
        'd3-random',
        'd3-sankey',
        'd3-scale',
        'd3-scale-chromatic',
        'd3-selection',
        'd3-selection-multi',
        'd3-shape',
        'd3-time',
        'd3-time-format',
        'd3-timer',
        'd3-transition',
        'd3-voronoi',
        'd3-zoom'
      ],

      // Format of generated bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#format
      format: 'umd',

      // Export mode to use
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#exports
      exports: 'named',

      // The name to use for the module for UMD/IIFE bundles
      // (required for bundles with exports)
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#modulename
      moduleName: 'd3-ngx-essentials',

      // See https://github.com/rollup/rollup/wiki/JavaScript-API#globals
      globals: {
        typescript: 'ts',
        'd3-array': 'd3',
        'd3-axis': 'd3',
        'd3-brush': 'd3',
        'd3-chord': 'd3',
        'd3-collection': 'd3',
        'd3-color': 'd3',
        'd3-contour': 'd3',
        'd3-dispatch': 'd3',
        'd3-drag': 'd3',
        'd3-dsv': 'd3',
        'd3-ease': 'd3',
        'd3-force': 'd3',
        'd3-format': 'd3',
        'd3-geo': 'd3',
        'd3-hierarchy': 'd3',
        'd3-interpolate': 'd3',
        'd3-path': 'd3',
        'd3-polygon': 'd3',
        'd3-quadtree': 'd3',
        'd3-queue': 'd3',
        'd3-random': 'd3',
        'd3-sankey': 'd3',
        'd3-scale': 'd3',
        'd3-scale-chromatic': 'd3',
        'd3-selection': 'd3',
        'd3-selection-multi': 'd3',
        'd3-shape': 'd3',
        'd3-time': 'd3',
        'd3-time-format': 'd3',
        'd3-timer': 'd3',
        'd3-transition': 'd3',
        'd3-voronoi': 'd3',
        'd3-zoom': 'd3'
      }

    }))
    .pipe(rename('d3-ngx-essentials.umd.js'))
    .pipe(gulp.dest(distFolder));
});
```

**Comment by sheldonyss** [comment]
Hi @jvandemo so sorry for the late reply. Actually, @sgentile 's comment was what confused me initially. You have already answered that. Thanks for the clarifications.

**Comment by jvandemo** [comment]
@sheldonyss &mdash; Thank you for your follow-up, much appreciated 👍

**Comment by chanm003** [comment]
@jvandemo I get an error when I try to import moment during the gulp task 'rollup:fesm'. 

'moment' is imported by build\httpBodyParser.js, but could not be resolved – treating it as an external dependency

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Cannot call a namespace ('moment')

**Comment by chanm003** [comment]
@tomwanzek Do I have to edit the gulpfile.js to use the moment library?  

One of my files has the following line:
import * as moment from 'moment';

But I get errors when the 'rollup:fesm' task runs.

I tried making following edits to gulpfile.js, but no luck:
```
globals: {
        typescript: 'ts',
        moment: 'moment'
}
```
```
external: [
        '@angular/core',
        '@angular/common',
        'moment'
]
```

**Comment by fishme** [comment]
did you try with `import moment from 'moment';`

I put it to external and it works.
