### ISSUE TITLE
Running tests fails

### ISSUE THREAD

**Issue by irundaia** [jvandemo/generator-angular2-library#156]
I ran this generator on an empty directory, and I tried to run the tests using `npm test`. 

This outputs the following to the console:

```
> tsc && karma start

src/sample.component.spec.ts(7,1): error TS2304: Cannot find name 'describe'.
src/sample.component.spec.ts(14,3): error TS2304: Cannot find name 'beforeEach'.
src/sample.component.spec.ts(28,3): error TS2304: Cannot find name 'it'.
src/sample.component.spec.ts(29,5): error TS2304: Cannot find name 'expect'.
```

**Comment by jvandemo** [comment]
Currently there is no official consensus yet (see #1) on how to structure unit tests. E.g. one library author may put all tests in a `tests` directory while another library author may put tests in the `src` directory.

Until there is a consensus, you can run:

```bash
$ karma init
```

from the root of your library to create your own Karma configuration.

As soon as there are official guidelines, we will also add a default karma configuration to this generator.

See https://github.com/jvandemo/generator-angular2-library#how-can-i-configure-karma for more information.

Meanwhile, you can already use Jest to run your unit tests, which is included in the latest version of this generator.

I will close this issue for now, but feel free to re-open if you feel it is needed.

Thanks!
