### ISSUE TITLE
No Directive annotation found on SampleComponent

### ISSUE THREAD

**Issue by sky-coding** [jvandemo/generator-angular2-library#16]
Getting `Error: No Directive annotation found on SampleComponent` when consuming generated library.

Steps to reproduces:

- run generator
- update Angular 2 to RC4
- rebuild
- `npm link` into another project (https://github.com/AngularClass/angular2-webpack-starter)
- `import {SampleComponent} from '<linked-library-name>';`
- include `SampleComponent` in a component's `directives` and use it on a page

Error: No Directive annotation found on SampleComponent

**Comment by jvandemo** [comment]
@sky-coding &mdash; What does your generated library code look like? Is it possible to post it here? Thanks in advance!

**Comment by sky-coding** [comment]
Hey @jvandemo, I just gave it another try. Deleting the library's `node_modules` folder resolves the error. It seems my consumer app is giving priority to the library's local `node_modules` folder. This would not be an issue when installing the library, but is an issue when using `npm link`. I don't think this is your issue.

**Comment by jvandemo** [comment]
@sky-coding &mdash; Thank you for updating the issue 👍
