### ISSUE TITLE
Property 'uniqueid' does not exist on type 'LoDashStatic'

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [jvandemo/generator-angular2-library#161]
I'm trying to bring in lodash so I can use uniqueid(). I've had no success. I get the error: Property 'uniqueid' does not exist on type 'LoDashStatic'

Does anyone know how to get lodash into a library?

Thanks.

**Comment by jvandemo** [comment]
@broweratcognitecdotcom &mdash; Did you manage to resolve your issue? Thanks!

**Comment by broweratcognitecdotcom** [comment]
Yes. I resolved this issue. It was not related to yo angular2-library. Thanks.

**Comment by jvandemo** [comment]
@broweratcognitecdotcom &mdash; Ok, great, thank you for the update! 👍
