### ISSUE TITLE
Including PrimeNg as 3rd Party Library is not working

### ISSUE THREAD

**Issue by quahkj** [jvandemo/generator-angular2-library#162]
Hi There,

I try to develop a simple library that includes PrimeNg UI components. For example, I have below HTML that includes PrimeNg button and accordion:

``` 
<div>
<h1>Simple Library</h1>
<button pButton type="button" label="Click" value=""(click)="onClick()"></button>
    <p-accordion>
        <p-accordionTab header="Header 1">
            Content 1
        </p-accordionTab>
        <p-accordionTab header="Header 2">
            Content 2
        </p-accordionTab>
        <p-accordionTab header="Header 3">
            Content 3
        </p-accordionTab>
    </p-accordion>
</div>
```
When I try to use this component in consumer application, it doesn't recognise the PrimeNg component - it just displays an empty button without label and plain text contents. I have imported all PrimeNg modules into consumer application app.module.ts. As mentioned in FAQ, I didn't included the PrimeNg in this library since it is not required. I am not sure this is the right way to go. Any help or advice is appreciated. Thank you.

**Comment by broweratcognitecdotcom** [comment]
Did you include the stylesheet?

"styles": [
  "../node_modules/font-awesome/css/font-awesome.min.css",
  "../node_modules/primeng/resources/primeng.min.css",
  "../node_modules/primeng/resources/themes/omega/theme.css",
  //...
],

**Comment by quahkj** [comment]
I tried two approaches: using "peerDependencies" and "devDependencies". If I included primeng in devDependencies and import the primeng components in index.ts in the library, it works - the primeng is shown on the consumer application. Of course, I have included the css you mentioned above as well in the consumer application which is using Angular CLI.

But if I included primeng in peerDependencies, the consumer application thrown below error on the web console:

```Uncaught Error: Template parse errors:
'p-accordionTab' is not a known element:
1. If 'p-accordionTab' is an Angular component, then verify that it is part of this module.
2. If 'p-accordionTab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<button pButton type="button" label="Library Btn"></button> <ng-content></ng-content> <p-accordion> [ERROR ->]<p-accordionTab header="Header 1"> Content 1 </p-accordionTab> <p-accordionTab header="Header 2"> Con"):
```
I included CUSTOM_ELEMENTS_SCHEMA in lib application to suppress this error but consumer application only display plain text because it can't recognise primeng tags. 

So I am wondering using peerDependencies as mentioned in FAQ is the correct way to include third party library or should I using devDependencies which is worked fine in my situation.

**Comment by jvandemo** [comment]
@quahkj &mdash; If you specify it as a peer dependency (primeng) in your library:

- a warning will be displayed when you run `npm install` in the consuming application and the peer dependency (primeng) is not installed
- the consuming application still needs to install  the peer dependency (primeng) by running `npm install primeng` and import the module into your Angular application module (by listing it in `imports` in application NgModule metadata)

It sounds like your consuming application does not have the module installed and imported.

**Comment by quahkj** [comment]
@jvandemo - Thanks for the comment. It seems like to make it works I have to include primeng in devDependencies as well beside peerDependencies. Here is what I did:

Library Application
============
1) Include primeng in package.json devDependencies.
2) Run npm install to get primeng
3) Import primeng components in index.ts
4) Write codes that include primeng components
5) Do npm run build and link it

Consumer application
==============
1) Create a consumer application with Angular CLI
2) Include primeng in package.json dependencies
3) Run npm install and link the library application
4) Use the selector from library and I can see the primeng components in consumer application

I am not quite sure this is the correct way to include 3rd party library. Hope you guys can help me to verify my works. Thank you.

**Comment by jvandemo** [comment]
@quahkj &mdash; The downside of that approach is that primeng will be installed multiple times if you have multiple libraries that each have primeng as a devDependency.

If you list primeng as a peer dependency, it will be installed only once.

Can you please try the following?

#### Library

1. Run `npm install primeng --save` to install primeng and add it as a devDependency to `package.json` in the root directory
2. Specify primeng as peerDependency in `src/package.json`, NOT as dependency or devDependency (`src/package.json` is the package.json that is distributed with your library, so we need to specify primeng as peer dependency here)
3. import primeng module in your library module
4. Write code that includes primeng components
5. Build library and link it

#### Consuming application

1. create application using Angular CLI
2. run `npm install yourlibrary` to install your library (which should show warning if primeng is not installed) or link it locally
3. run `npm install primeng` to install primeng
4. import primeng module in `AppModule`
5. import your library module in `AppModule`
6. use your library components

Can you let me know how that goes?

Thanks!

**Comment by quahkj** [comment]
@jvandemo - The suggested approach is worked. Thanks. But I didn't publish the library to npm, instead I use npm link to link the library from consumer. Just curious, is it a technical requirement to publish all libraries to npm? Sometimes we don't want to publish there (don't want make it publicly available and small team) and npm link is just sufficient to consume the library. Another thing is I didn't import primeng module in consumer application and it works as well.

**Comment by jvandemo** [comment]
@quahkj &mdash; Thank you for the confirmation.

> Just curious, is it a technical requirement to publish all libraries to npm?

If you are working on a local project, linking should also work. However, if you need to share code online, publishing your library privately or publicly on the npm registry is probably more convenient.

> Another thing is I didn't import primeng module in consumer application and it works as well.

If your library exports an Angular module, then your consuming Angular application does not explicitly have to import the exported Angular Module. It would be automatically imported when the consuming application imports your library. See the [offical Angular module FAQ](https://angular.io/guide/ngmodule-faq) for more information.

Thanks again for the update!
