### ISSUE TITLE
Create a step-by-step guide for creating Angular 4 packages on non-Angular dependencies

### ISSUE THREAD

**Issue by kktam** [jvandemo/generator-angular2-library#164]
This is not a bug report, but an enhancement on documentation.

Following [issue 159](https://github.com/jvandemo/generator-angular2-library/issues/159). It would be beneficial to create step by step to cover how to import non angular dependencies and provide a place-holder to include samples for anyone who like to contribute to this effort.

The goal of this is to show, how to use other non Angular libraries to use in an Angular project.

I am interested in writing this guide. Please let me know the next step.

the guide may begin with help on integrating [FullCalendar.io](https://github.com/jvandemo/generator-angular2-library/issues/147) using generator-angular2-library, which is a very popular library. The list may grows as we add other into the list.

**Comment by broweratcognitecdotcom** [comment]
I would like this. I think it is sort of a mystery when a develop who is using this generator must add to devDependencies, dependencies, and peerDependencies. I managed to get everything working, but other devs here are struggling.

**Comment by quahkj** [comment]
This is a good suggestion. I try to include third party library into peer dependency but it doesn't worked as mentioned in the FAQ. Then I tried to include in dev dependency and it just worked. I am a bit confuse which one should be used.

**Comment by jvandemo** [comment]
@quahkj &mdahs; Can you please check https://github.com/jvandemo/generator-angular2-library/issues/162#issuecomment-319937878. Thanks!

**Comment by jvandemo** [comment]
@kktam &mdash; Thank you, that sounds wonderful. Feel free to create a PR and publish a guide in a `guides` directory.

If you need any help, don't hesitate the let us know.

Much appreciated!
