### ISSUE TITLE
Injecting a external Script

### ISSUE THREAD

**Issue by pratikthecook** [jvandemo/generator-angular2-library#168]
Hi i am building a library using google charts but im now confused as to how to i inject it into my library's module. FYI i have read your readme on **What if my library depends on a third party library?** 
But lets say i want to use a xyz.js which isnt on NPM, then how should i proceed with this?

I did find a way around but it isnt working(for obvious reason) by writing this in a Injectable class
  
```
let script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://www.gstatic.com/charts/loader.js';
document.getElementsByTagName('head')[0].appendChild(script);
```

And the DOMSanitzer runs and removes it... so now i am clueless

**Comment by jvandemo** [comment]
@pratikthecook &mdash; If you have a CDN hosted library, then I think it would make sense to have the consuming application include the script to load the dependency. Would that work in your scenario?

Or do I misunderstand your question? Thanks!

**Comment by pratikthecook** [comment]
Yes, but that would burden the consuming application developer to include every single JS from CDN into his/her app. Here's The link to library created using your generator(its a pretty awesome generator :1st_place_medal: ) [Amexio](https://github.com/meta-magic/amexio.github.io/) so now i need lot of stuff which i dont want the user to burden rather inject it the module itself. 
Hope i made the point clear. Thanks

**Comment by Janatbek** [comment]
In my case I am directly pointing to node_modules/my-library/assets/3party.js in angular-cli or in the head of index.html

**Comment by kktam** [comment]
@pratikthecook  I have found this thread may be of help to you [Load JS Script in Angular2+](https://stackoverflow.com/questions/34489916/load-external-js-script-dynamically-in-angular-2)

You cannot reference DOM directly in Angular 4 components. You will either need to use ref elements, or indirectly access DOM using JQuery. I have a [Example](https://github.com/kktam/fullcalendar-ag4/blob/fullcalendar-ag4/src/calendar.component.ts) project that demonstrate how to setup JQuery in projects created by generator-angular2-library.

**Comment by pratikthecook** [comment]
@kktam Thanks for your input, ive implemented it and then calling to scripts method on certain observables. please check the below https://github.com/meta-magic/amexio.github.io/blob/v2.0/src/modules/charts/src/chart.loader.service.ts

Since the issue is resloved i am closing this issue.

**Comment by justforuse** [comment]
@kktam Hi, Have you ever used jquery-ui in projects created by generator-angular2-library?
