### ISSUE TITLE
using json2typescript in an Angular library (yeoman-generator) causes compilation failed

### ISSUE THREAD

**Issue by kirakishin** [jvandemo/generator-angular2-library#169]
Hello,
iam facing to a problem using the package https://github.com/dhlab-basel/json2typescript in an Angular library generated by yeoman.

adding the dependency is ok, but when i start to compile with `npm run build` after created a decorated class, i got the error (rootDir error) : 
```bash
...
Error File 'C:/git/github/kirakishin/json2typescript-with-generator-angular2-library/node_modules/json2typescript/src/json2typescript/json-convert.ts' is not under 'rootDir' 'C:/git/github/kirakishin/json2typescript-with-generat
or-angular2-library/.tmp'. 'rootDir' is expected to contain all source files.
Error File 'C:/git/github/kirakishin/json2typescript-with-generator-angular2-library/node_modules/json2typescript/src/json2typescript/json-custom-convert.ts' is not under 'rootDir' 'C:/git/github/kirakishin/json2typescript-with-
generator-angular2-library/.tmp'. 'rootDir' is expected to contain all source files.

[00:53:47] 'ngc' errored after 1.51 s
[00:53:47] Error: ngc compilation failed
    at ngc.then (C:\git\github\kirakishin\json2typescript-with-generator-angular2-library\gulpfile.js:59:15)
ERROR: ngc compilation failed
...
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! json2typescript-with-generator-angular2-library@0.1.0 build: `gulp build`
npm ERR! Exit status 1
```
my class is in `generic.model.ts`: 
```typescripts
import {JsonObject, JsonProperty} from "json2typescript";


@JsonObject
export default class GenericModel {
    @JsonProperty("name", String)
    name: string = undefined;
}

```

You can reproduce it by cloning : 
https://github.com/kirakishin/json2typescript-with-generator-angular2-library
then : 
- `npm install`
- `npm run build`

i don't unterstand the problem : it seems the compiler wants to compile *.ts file from json2typescript.
The same appears if i only import the lib without using it : 
```typescripts
import {JsonObject, JsonProperty} from "json2typescript";
```

could you help me please ?

thanks a lot

**Comment by kirakishin** [comment]
linked issue : https://github.com/dhlab-basel/json2typescript/issues/25

**Comment by kktam** [comment]
@kirakishin  it appears the ngc have some issues with experimentalDecorators, which is used in [json2typescript](https://github.com/dhlab-basel/json2typescript).

In general ngc does have a few very big issues right now, and one of them appears to be it does upgraded enough to support experimentalDecorators flag in TypeScript.

You can see a list of issues below:

[experimentalDecorators flag seemingly not accepted from tsconfig.json](https://github.com/Microsoft/TypeScript/issues/10084)

[ngc in compiler-cli does not work after upgrade to angular 4](https://github.com/angular/angular/issues/16944)

[experimentalDecorators warning appearing even with tsconfig.json](https://github.com/Microsoft/vscode/issues/9232)

It appears this is an Angular 4 problem, and not related to generator-angular2-library. You may not be able to use this library for Angular 4 until someone fix this.

**Comment by jvandemo** [comment]
The author of the library should push types to DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped

Once the types are in the type repository, you can install them in your library as a dev dependency using:

```
npm install @types/json2typescript --save-dev
```

You will also have to list json2typescript as a peer dependency in src/package.json to ensure that the consuming application has json2typescript installed.

I will close this issue because it is not directly related to this generated.

Feel free to re-open if needed. Thanks!
