### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by quahkj** [jvandemo/generator-angular2-library#170]
Hi @jvandemo ,

I known this issue was raised before in #113 but looks like this problem is happened again in the latest Angular CLI. Below is the version I am using:

Node - 6.11.2
Npm - 5.3.0
Angular cli - 1.3.0

How to reproduce:
1) Generate the sample library using yo angular2-library
2) Build the library - npm run build
3) Link the library - npm link
4) Generate consumer app using angular cli - ng new testsample
5) Import the sample library - npm link samplelib
6) Import samplelib module in app.mddule.ts of consumer app
7) Change the content of src/tsconfig.app.json as mentioned in FAQ
8) Start the consumer app using ng serve

Below is the src/tsconfig.app.json content:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [],
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

I am not sure I missed any things else. I have a  second environment which is working correctly: Node 6.10.0, Npm 5.3.0, Angular Cli 1.0.2.

Below is the screen shot of the error. Any clue?
<img width="1275" alt="screen shot 2017-08-14 at 4 33 40 pm 1" src="https://user-images.githubusercontent.com/7721312/29260697-cd19825a-810e-11e7-8e82-189c4a3671fd.png">

Thanks.

**Comment by daslaf** [comment]
I can confirm this is also happening to me

**Comment by saberhamidi** [comment]
Same happening to me also after i updated Angular CLI

**Comment by NetanelBasal** [comment]
+1

**Comment by leahcnels** [comment]
+1

**Comment by jvandemo** [comment]
Thank you for reporting.

Related issue: https://github.com/angular/angular-cli/issues/7384.

**Comment by saberhamidi** [comment]
if you can please come with a solution it will make my day. This error seems to be affecting a lot of people

**Comment by jvandemo** [comment]
When you `npm link` a library with peer dependencies, the consuming application will search for the peer dependencies in the library's parent directories instead of the application's parent directories.

Can you please try:

```
$ ng serve --preserve-symlinks
```

to make sure the consuming application searches for the peer dependencies in the application's node_modules directory?

Can you let me know if that works?

Thanks!!

**Comment by jvandemo** [comment]
Related article: http://codetunnel.io/you-can-finally-npm-link-packages-that-contain-peer-dependencies.

**Comment by saberhamidi** [comment]
I even run "ng serve --preserve-symlinks" and the problem still not solved. 

before it was working well, however when I updated my Angular CLI from 1.1.1 to version 1.3.0 and tried to run the application, I encountered that error in my browser console. but when running 'ng serve' the application compiles successfully, however, the browser throws that error. 

https://github.com/saberhamidi/Cloud7Shisha 

the above link is my project in github, if you can please clone it and run it yourself, and see what is really happening. make sure you run it with Angular CLI version 1.3.0, and please let me know if you find the cause of it. 

thanks @jvandemo

**Comment by quahkj** [comment]
Good news! The --preserve-symlinks option is worked for both ng serve and ng builld. Now the error is gone and it works as expected. 

I found the below configuration is no longer required as well:

```
{
  "compilerOptions": {
    // ...
    // Note: these paths are relative to `baseUrl` path.
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  }
}
```
Thanks a lot @jvandemo and I appreciate that.

**Comment by saberhamidi** [comment]
glad that it worked for you, but i am still struggling :(,

**Comment by NetanelBasal** [comment]
Yes, it works. I think we should add this to the documentation.

**Comment by osahner** [comment]
worked for me too.

**Comment by jvandemo** [comment]
@quahkj; @NetanelBasal, @osahner &mdash; Thank you for the confirmations, much appreciated! 👍 

@saberhamidi &mdash; Is it possible to share your code so we can help you figure out what could be wrong? It could also be structure related, see https://github.com/angular/angular-cli/issues/7384. Thanks!

**Comment by saberhamidi** [comment]
@quahkj I have included a github link of my project on my previous comment, you can use it to download my code and try it yourself.

**Comment by saberhamidi** [comment]
i spend the whole day trying to find the cause of that error, but failed :(

**Comment by quahkj** [comment]
@saberhamidi - I suggest you create a new sample library project and a new angular cli project in your existing environment and try it out. Make sure it is worked in your environment first - just isolate any env related issue.

**Comment by shanthece** [comment]
I can confirm this exactly happening to me

**Comment by jvandemo** [comment]
@shanthece &mdash; Can you try:

```
$ ng serve --preserve-symlinks
```

to see if that fixes your problem?

**Comment by saberhamidi** [comment]
@shanthece did you have a look at the problem?

**Comment by NetanelBasal** [comment]
Try to update the @angular/cli and generate a new project, this is what fix my problem.

**Comment by NetanelBasal** [comment]
The frustrating thing is that there is no automatic refresh even with `build:watch`.

**Comment by daslaf** [comment]
@NetanelBasal Yes! It's freaking annoying having to re-run `ng serve` each time something changes in the package

**Comment by quahkj** [comment]
@NetanelBasal , @daslaf 

Actually the npm run build:watch and npm start are working as expected - when library code is changed the npm run build:watch will detect it and rebuild the codes. After that, npm start on the consumer application should refresh as well but there are few tricks:

Library application:
1) Build the library application to make sure there is no error - npm run build
2) Link the src directory of library application into global node modules - npm link src 
3) Watch the code changes - npm run build:watch

Consumer application:
*Assume you are using angular CLI
1) Create a new app - ng new myproject
2) Edit package.json and change this line: "start": "ng serve" to "start": "ng serve --poll 10000 --preserve-symlinks".  
3) Start the app using "npm start" instead of "ng serve"

Now both lib and consumer app are ready and will refresh if there are any code changes. Try to change some codes in lib, you should see the console is rebuilding instantly. After few seconds, consumer app will kick in by restarting the app and finally browser refresh. Whole process is fully automated. Hope this help.

**Comment by NetanelBasal** [comment]
OK, thanks, we will check it out. By the way, this thread needs to be added to the README file.

**Comment by jvandemo** [comment]
@NetanelBasal, @daslaf Playground is coming soon with #146 👍

**Comment by Janatbek** [comment]
In my case my consuming app brakes when it tries to bring css and js from assets of library. 
Everything works. Library in watch mode, consuming app detects changes. But, it fails on assets. Can someone tell me workarounds?

**Comment by tarunlv** [comment]
I had the same problem from last 2 days.
You just have to upgrade/downgrade your @angular/cli to @angular/cli@1.2.7
run{ npm install @angular/cli@1.2.7 }
