### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by Ludevik** [jvandemo/generator-angular2-library#175]
After following install instructions and running `npm test` i get:

`
> library-test@0.1.0 test C:\development\projects\library-test
> tsc && karma start
src/sample.component.spec.ts(7,1): error TS2304: Cannot find name 'describe'.
src/sample.component.spec.ts(14,3): error TS2304: Cannot find name 'beforeEach'.
src/sample.component.spec.ts(28,3): error TS2304: Cannot find name 'it'.
src/sample.component.spec.ts(29,5): error TS2304: Cannot find name 'expect'.
npm ERR! Test failed.  See above for more details.
`

I chose karma + jasmine during setup.

**Comment by Janatbek** [comment]
It's typing issue. Add jasmine and node to types in tsconfig.spec.json

**Comment by Janatbek** [comment]
Can you show me your setup? Or git repo?

**Comment by jvandemo** [comment]
Currently, there is no official consensus yet (see #1) on how to structure unit tests. E.g. one library author may put all tests in a `tests` directory while another library author may put tests in the `src` directory.

Until there is a consensus, you can run:

```bash
$ karma init
```

from the root of your library to create your own Karma configuration.

As soon as there are official guidelines, we will also add a default karma configuration to this generator.

See https://github.com/jvandemo/generator-angular2-library#how-can-i-configure-karma for more information.

Meanwhile, you can already use Jest to run your unit tests, which is included in the latest version of this generator.

I will close this issue for now, but feel free to re-open if you feel it is needed.

Thanks!
