### ISSUE TITLE
Unexpected value 'SampleModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by gatimus** [jvandemo/generator-angular2-library#177]
`npm run build`
`cd .\dist`
`npm link`

From @angular/cli@1.3.2 project add:
src/tsconfig.app.json
```
  "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
```
src/app/app.module.ts
```
import { SampleModule } from 'lib';
...
  imports: [
    BrowserModule,
    SampleModule
  ],
...
```

`npm link [lib-name]`
`npm start`

`Unexpected value 'SampleModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

**Comment by liuxh0** [comment]
I also have the same problem.

**Comment by Janatbek** [comment]
Are you exporting it from libmodule?

**Comment by Janatbek** [comment]
npm start --preserve-symlinks should solve it

**Comment by gatimus** [comment]
@Janatbek I had tried `npm start --preserve-symlinks` but I doesn't work for me. I have to do `ng serve --preserve-symlinks`.

**Comment by Janatbek** [comment]
I wrote npm start because you mentioned it. otherwise, I always run ng serve. did it work?

**Comment by gatimus** [comment]
@Janatbek yes `ng serve --preserve-symlinks` works
