### ISSUE TITLE
How do I add a polyfill to a generated angular2 library?

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [jvandemo/generator-angular2-library#182]
I'd like to add this polyfill to a library. https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill

How would I do that? Thank you.

**Comment by broweratcognitecdotcom** [comment]
Was my question inappropriate or just plain stupid?

**Comment by broweratcognitecdotcom** [comment]
This is essential to my success. Does anyone know the answer? Thank you.

**Comment by jvandemo** [comment]
@broweratcognitecdotcom &mdash; Did you figure it out? If so, would you mind sharing so others can benefit from your learnings? Thanks!

**Comment by broweratcognitecdotcom** [comment]
Solution is quite simple: import the polyfill as the first import in index.js:

import 'intersection-observer';
import { NgModule, ModuleWithProviders, NO_ERRORS_SCHEMA } from '@angular/core';
.
.
.

**Comment by jvandemo** [comment]
@broweratcognitecdotcom &mdash; Awesome, thank you for sharing 👍
