### ISSUE TITLE
having issue on build for latest rollup

### ISSUE THREAD

**Issue by aelbore** [jvandemo/generator-angular2-library#186]
options.entry is deprecated, use options.input

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/Users/ui-dev/Desktop/generator/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/Users/ui-dev/Desktop/generator/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10154:14)
    at Object.rollup (/Users/ui-dev/Desktop/generator/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10225:3)
    at /Users/ui-dev/Desktop/generator/node_modules/gulp-rollup/index.js:149:23
    at Array.map (native)
    at /Users/ui-dev/Desktop/generator/node_modules/gulp-rollup/index.js:138:37
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by deepak-ui-stack** [comment]
Hello Please try to change the moduleName to name which will resolve your issue.

gulp.task('taskname', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
    // transform the files here.
    .pipe(rollup({

      // Bundle's entry point
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#entry
      input: `${buildFolder}/index.js`,

      // A list of IDs of modules that should remain external to the bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#external
      external: [
        '@angular/core',
        '@angular/common'
      ],

      // Format of generated bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#format
      format: 'umd',

      // Export mode to use
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#exports
      exports: 'named',

      // The name to use for the module for UMD/IIFE bundles
      // (required for bundles with exports)
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#modulename
      name: 'modulename', ==> change to this
      // moduleName: 'modulename', ==> remove this

      // See https://github.com/rollup/rollup/wiki/JavaScript-API#globals
      globals: {
        typescript: 'ts'
      }

    }))
    .pipe(rename('stateauto-header.umd.js'))
    .pipe(gulp.dest(distFolder));
});

**Comment by deepak-ui-stack** [comment]
Hello Please try to change the moduleName to name which will resolve your issue. @aelbore 

gulp.task('rollup:umd', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
    // transform the files here.
    .pipe(rollup({

      // Bundle's entry point
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#entry
      input: `${buildFolder}/index.js`,

      // A list of IDs of modules that should remain external to the bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#external
      external: [
        '@angular/core',
        '@angular/common'
      ],

      // Format of generated bundle
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#format
      format: 'umd',

      // Export mode to use
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#exports
      exports: 'named',

      // The name to use for the module for UMD/IIFE bundles
      // (required for bundles with exports)
      // See https://github.com/rollup/rollup/wiki/JavaScript-API#modulename
      name: 'modulename', ==> change to this
      // moduleName: 'modulename', ==> remove  

      // See https://github.com/rollup/rollup/wiki/JavaScript-API#globals
      globals: {
        typescript: 'ts'
      }

    }))
    .pipe(rename('rename.umd.js'))
    .pipe(gulp.dest(distFolder));
});

**Comment by aelbore** [comment]
@deepak-ui-stack will try this. thanks anyway

**Comment by aelbore** [comment]
@deepak-ui-stack it works for me. we can close this.
