### ISSUE TITLE
error while running "npm run build"

### ISSUE THREAD

**Issue by sowmya108** [jvandemo/generator-angular2-library#192]
options.entry is deprecated, use options.input

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/var/www/html/hello/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/var/www/html/hello/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10154:14)
    at Object.rollup (/var/www/html/hello/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:10225:3)
    at /var/www/html/hello/node_modules/gulp-rollup/index.js:149:23
    at Array.map (<anonymous>)
    at /var/www/html/hello/node_modules/gulp-rollup/index.js:138:37
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mmaatt99** [comment]
I have the same problem

**Comment by iean** [comment]
It literally started happening from today . Me facing the same issue building the project

**Comment by iean** [comment]
https://github.com/jvandemo/generator-angular2-library/issues/186

Same issue I think. Should try this.

**Comment by iean** [comment]
@sowmya108  @mmaatt99 Find the gulp task for **

> gulp.task('rollup:umd'

There is a property naming called module name 
![image](https://user-images.githubusercontent.com/1315432/30396404-51a54bdc-98eb-11e7-8669-c1aeda6a139d.png)

change it to the following .
**
![image](https://user-images.githubusercontent.com/1315432/30396303-ff5739c6-98ea-11e7-99d8-310b2fd3d31b.png)

**Comment by matheusdavidson** [comment]
Thank you @iean, it works!

**Comment by jvandemo** [comment]
Thank you, version 11.4.0 has been released with a fix (see #190) 👍
