### ISSUE TITLE
npm run build issue

### ISSUE THREAD

**Issue by plambhsa** [jvandemo/generator-angular2-library#194]
I created a new library using this generator, and then after adding my code and running npm run build, an error occurred. To fix it, go to the gulpfile and then to the rollup:umd task and  change moduleName to name. That takes the error right away.

There's also a notice of deprecation for having "entry" in that same task instead of "input". But it'll still run with entry.

I would do this by myself, and submit the PR, but I don't know if others are running into the same issue.

**Comment by ydornala** [comment]
@plambhsa Yes i'm running into the same issue.

**Comment by jvandemo** [comment]
@plambhsa Thank you, version 11.4.0 has been released with a fix (see #190) 👍
