### ISSUE TITLE
Can not find module from "@scope/lib-name" - Have to use "@scope/lib-name/dist" 

### ISSUE THREAD

**Issue by crebuh** [jvandemo/generator-angular2-library#196]
Hey Guys, I got the following problem. 

I'm not able to import my module like this

> import { AngularUiModule } from '@scope/angular-ui';

instead I have to import from the dist folder

import { AngularUiModule } from '@scope/angular-ui/dist';

any idea on how to fix this?

**Comment by crebuh** [comment]
Sorry my  bad instead of using 

> npm publish

inside the dist folder, I used it inside the root folder :see_no_evil:

**Comment by jvandemo** [comment]
@crebuh &mdash; Could it be that you did not run `npm publish` from the `dist` directory?

**Comment by jvandemo** [comment]
Ah, your comment crossed mine. Looks like you solved it already 👍
