### ISSUE TITLE
Rollup Error in Gulpfile

### ISSUE THREAD

**Issue by abalad** [jvandemo/generator-angular2-library#197]
Gulpfile is generating the following error with the new version of the rollup:

`options.entry is deprecated, use options.input

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, intero
p, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, wat
ch
`

**Comment by abalad** [comment]
I found the solution .. should be changed the following things within gulpfile:

https://github.com/udos86/ng-dynamic-forms/issues/494
or 
https://github.com/rollup/rollup/issues/1479

**Comment by jvandemo** [comment]
@abalad &mdash; This was fixed in #190 and was released as v11.4.0. If you update your generator to the latest version, it should be okay 👍  Thanks!
