### ISSUE TITLE
publishing npm issue

### ISSUE THREAD

**Issue by geoffrey-gaurav** [jvandemo/generator-angular2-library#200]
i am not able to publish my module next version
admin1@PC-131:/home1/lamppp/htdocs/nethues-charts$ npm publish dist
npm ERR! publish Failed PUT 403
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "dist"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code E403

npm ERR! You cannot publish over the previously published version 0.1.0. : nethues-charts
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/lamppp/htdocs/nethues-charts/npm-debug.log

**my package.json**
{
  "name": "nethues-charts",
  "version": "0.1.2",
  "scripts": {
    "build": "gulp build",
    "build:watch": "gulp",
    "docs": "npm run docs:build",
    "docs:build": "compodoc -p tsconfig.json -n nethues-charts -d docs --hideGenerator",
    "docs:serve": "npm run docs:build -- -s",
    "docs:watch": "npm run docs:build -- -s -w",
    "lint": "tslint --type-check --project tsconfig.json src/**/*.ts",
    "test": "tsc && karma start"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/geoffrey-gaurav/nethues-charts"
  },
  "author": {
    "name": "Gaurav Rathee",
    "email": "geoffrey@123789.org"
  },
  "keywords": [
    "angular",
    
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/username/repo/issues"
  },
  "devDependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@compodoc/compodoc": "^1.0.0-beta.10",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "core-js": "^2.4.1",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-rename": "^1.2.2",
    "gulp-rollup": "~2.11.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.5.2",
    "node-sass-tilde-importer": "^1.0.0",
    "node-watch": "^0.5.2",
    "protractor": "~5.1.0",
    "rollup": "^0.41.6",
    "run-sequence": "^1.2.2",
    "rxjs": "^5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0",
    "zone.js": "^0.8.4"
  },
  "engines": {
    "node": ">=6.0.0"
  }
}

**Comment by dbfannin** [comment]
@geoffrey-gaurav, there are 2 package.json files. One inside of the root directory (the one displayed above from the root directory), the other is inside your src directory. 

The package.json file that is used when publishing your module is the one located in the src directory. You will need to updated src/package.json to your new version number, and then re-build and publish your library and you should be good to go.

**Comment by jvandemo** [comment]
@geoffrey-gaurav &mdash; @dbfannin is right. Have you tried updatnig `src/package.json` yet? Thanks!

**Comment by Janatbek** [comment]
I had to update both package.json files

**Comment by geoffrey-gaurav** [comment]
@dbfannin thanx man. it works
