### ISSUE TITLE
linting fails

### ISSUE THREAD

**Issue by jbrecht** [jvandemo/generator-angular2-library#21]
Two problems occur when attempting to run lint:

1. Codelyzer fails to parse the TypeScript version properly:
```
/Users/JohnBrecht/dev/ng2-lib-test/node_modules/codelyzer/util/syntaxKind.js:1480
                throw new Error('Unsupported TypeScript version: ' + ts.version);
                ^
Error: Unsupported TypeScript version: 2.0.2
```

This can be fixed my bumping the codelyzer version in package.json to ^0.0.28.

2. One running properly, then there is a lint failure:
`src/sample.component.ts[4, 13]: The selector of the component "SampleComponent" should be named kebab-case (https://goo.gl/mBg67Z)`

Which is easily fixed by changing line 4 of sample.component.ts to read:
`  selector: 'sample-component',`

**Comment by jvandemo** [comment]
@jbrecht &mdash; Just released v3.0.4 with a fix. Thank you for reporting! Much appreciated 👍
