### ISSUE TITLE
Issues with index exports and NG >4.4.4

### ISSUE THREAD

**Issue by axtho** [jvandemo/generator-angular2-library#220]
Hi there,

Thanks for this great starter. It has been really helpful.

In my project I am using a core library, which shares services and Redux (NgRX) files between the Web and the Mobile App. For this purpose I have split the files into subdirectories (NgRX creates much boilerplate), which have index.ts files that export the .ts files contained. [Example](https://github.com/digitaldeacon/memberhive2/tree/master/core/src/modules/person).

In the main index.ts I am doing the following:

```TS
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GeocodeService } from './services/geocode.service';
import { HttpService } from './services/http.service';
import { LoginService } from './services/login.service';

export * from './services/geocode.service';
export * from './services/http.service';
export * from './services/login.service';
export * from './modules/person';
export * from './modules/auth';
export * from './modules/interaction';
export * from './modules/settings';
export * from './modules/tags';
export * from './common';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [
  ],
  exports: [
  ]
})
export class MhCoreModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MhCoreModule,
      providers: [GeocodeService, HttpService, LoginService]
    };
  }
}
```
Up until Angular 4.4.5 this used to just work. With 4.4.5 (presuming that it is the compiler here, since ngc fails) the compilation process issues errors with the subfolders:

```
Error: Could not resolve './modules/person' from build/index.js
    at error (/Applications/MAMP/htdocs/memberhive2/core/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/Applications/MAMP/htdocs/memberhive2/core/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:9804:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
```
Maybe you can have a look into this since Angular is busy changing the compiler quite a bit (with view of NG5 being in RC now).

I am lost for solutions, except for fixing NG at 4.4.4.

**Comment by raphael-volt** [comment]
Try this :
```ts
export * from './modules/person/index';
```

**Comment by axtho** [comment]
@raphael-volt Thanks, that did the trick. But why??
