### ISSUE TITLE
 Cannot call a namespace ('moment')

### ISSUE THREAD

**Issue by sheldonyss** [jvandemo/generator-angular2-library#221]
My library uses moment `import * as moment from 'moment'`.

When I run `gulp compile` I hit this error. 
`
Error: Cannot call a namespace ('moment')
    at error (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:8170:3)
    at CallExpression.bind (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:6324:17)
    at eachChild.child (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5674:34)
    at keys.forEach.key (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5685:5)
    at Array.forEach (native)
    at ConditionalExpression.eachChild (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5678:13)
    at ConditionalExpression.bind (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5674:8)
    at eachChild.child (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5674:34)
    at keys.forEach.key (C:\SourceCodeNew\IndConsoleSvcProxy\node_modules\rollup\dist\rollup.js:5685:5)
`

This [SO ](https://stackoverflow.com/a/40346098/466369) post suggesting change the import to `import moment from 'moment'` but it doesn't work for me because I hit another error `Module '"C:/SourceCodeNew/IndConsoleSvcProxy/node_modules/moment/moment"' has no default export.`

**Comment by sheldonyss** [comment]
Need to add this to tsconfig.es5.json "allowSyntheticDefaultImports": true

**Comment by Ismaestro** [comment]
Same problem, @sheldonyss that does not works!

**Comment by Ismaestro** [comment]
My workarround:

```
import * as moment_ from 'moment';

const moment = moment_;
```

:)

**Comment by dave0688** [comment]
Wow, thanks @Ismaestro.
Really wondering how you found that out... :D

**Comment by Ismaestro** [comment]
From [here](https://github.com/rollup/rollup/issues/670#issuecomment-281139978). ;)

**Comment by logic01** [comment]
With Angular 6 this workaround no longer works.

import * as moment_ from 'moment';
const moment = moment_;

Cannot call a namespace ('moment_')
Error: Cannot call a namespace ('moment_')

**Comment by Ismaestro** [comment]
Hi @logic01 , for me it's working with v6, [here](https://github.com/Ismaestro/angular6-example-app). What versions are you using? (ng -v)

<img width="849" alt="screen shot 2018-05-08 at 18 40 21" src="https://user-images.githubusercontent.com/10084945/39770499-7e773dfa-52ef-11e8-9c44-5431fec59f33.png">

**Comment by Ismaestro** [comment]
👍 Yes moment save my days when I have to work with dates...

**Comment by jvandemo** [comment]
@Ismaestro @logic01 &mdash; Thank you for the update 👍

**Comment by KissBalazs** [comment]
This workaround worked for us with Angular 6, but now broken again in Angular 7.

**Comment by alsoicode** [comment]
I'm having the same issue as @KissBalazs with Angular 7

**Comment by westandy-dcp** [comment]
this same issue pops up with `import * as format from 'date-fns/format';` and the solution is the same:

```
import * as format_ from 'date-fns/format';
const format = format_;
```

What is special about moment and date-fns that typescript chokes like this?  Like someone said earlier, I thought TS was a superset of JS?

**Comment by tanzeelrana** [comment]
```
import * as moment_ from "moment";

const moment = moment_;
```
works for me on a fresh build for an angular 7 project

**Comment by will-wow** [comment]
FWIW, I ran into a similar problem, and solved it by adding 

```json
"esModuleInterop": true,
```
to my `tsconfig.json`. That lets you just `import library from "library"` from CommonJS libraries, instead of `import * as library from 'library'`, and seems to be a little more forgiving to libraries that otherwise give Typescript trouble

**Comment by hlpupo** [comment]
> My workarround:
> 
> ```
> import * as moment_ from 'moment';
> 
> const moment = moment_;
> ```
> 
> :)

thank you so much, awesome solution

**Comment by frynsen1986** [comment]
On a project I'm working on we had luck importing 'moment' like this:
`import moment, {Moment} from 'moment';`

Tests run fine, and the command `ng build <project>` builds fine.

The setup we're working in is as follows:
- Angular: 8.2.13
- Typescript: 3.5.3
- moment: 2.24.0
