### ISSUE TITLE
Error when importing third party library

### ISSUE THREAD

**Issue by casni14** [jvandemo/generator-angular2-library#225]
I'm trying to use ng-bootstrap in my library, but get the error:
`GET http://localhost:3000/@ng-bootstrap/ng-bootstrap 404 (Not Found)`
`Error: Fetch error: 404 Not Found 
Instantiating http://localhost:3000/@ng-bootstrap/ng-bootstrap
  Loading http://localhost:3000/dist/my-library.umd.js
  Loading .playground/index.js
    at fetch.js:37
    at ZoneDelegate.invoke (zone.js:392)
    at Zone.run (zone.js:142)
    at zone.js:873
    at ZoneDelegate.invokeTask (zone.js:425)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at <anonymous>`
I have followed the quickstart guide, after building and running npm run playground to check if everything is working, I installed @ng-bootstrap/ng-bootstrap through npm as described in the faq's and added it as a peer-dependency. But when I import and add NgbModule in index.ts the browser throws the error above.

**Comment by alesmit** [comment]
@casni14 had the same problem. I solved mapping the 3rd party lib dependency in **playground/systemjs.config.js**

**Comment by izifortune** [comment]
@casni14  I'm closing this issue feel free to reopen

**Comment by kamalkech** [comment]
@alesmit : how ?
