### ISSUE TITLE
How to import any Javascript libraries from NPM and use it as described in their documentation

### ISSUE THREAD

**Issue by Janatbek** [jvandemo/generator-angular2-library#227]
I want to use this library to create a directive on top of some JS libraries in NPM. but when I install it and import, it says has no exported member. or other errors.

**Comment by IckleChris** [comment]
Have you followed the instructions in [this guide](https://github.com/jvandemo/generator-angular2-library/blob/master/guides/import_non_angular_libraries.md)?

**Comment by izifortune** [comment]
@Janatbek  I'm closing the issue feel free to reopen it
