### ISSUE TITLE
<package-name> has no exported member SampleModule

### ISSUE THREAD

**Issue by beeman** [jvandemo/generator-angular2-library#23]
First of all thanks for creating this project!

I'm trying to create a library that has a few components. Using version 3.0.4 of this generator I've created my library. When I try to include the library in my application I get an error:

```
Module '"/path/to/angular-sample-app/node_modules/angular-sample-module/dist/index"' 
has no exported member 'SampleModule'.
```

The fix for this is quite simple, changing `export default class SampleModule` to `export class SampleModule` makes it work.

I was wondering if this is expected behavior or if the generator should actually export the class without it being `default`?

If the latter is the case, please consider my PR. Thanks!

**Comment by AbigailFernandes** [comment]
I am facing a similar problem. I have published the library to npm. I am trying to use it in my own application. I am not very sure if I am importing it correctly. 
I did change `esport default class SampleModule` to `export class SampleModule` I am using SystemJs and not Webpack, and importing it in my application like this 
`import { SampleModule } from "../node_modules/ng2-reviewcomponent-test/dist/index";`
I am not sure if I have imported it correctly. I have not made any change to the component, that came with angular2-genrator-library

**Comment by jvandemo** [comment]
@beeman I have updated the template file and released v4.0.0 to fix the issue. 

Thank you for reporting. Much appreciated! 👍

**Comment by jvandemo** [comment]
@AbigailFernandes &mdash; Can you create a plunk with your sample application so we can have a look at it and create a new issue for it (the current issue is closed because it relates to a different issue that is now fixed)?

Thanks in advance! 👍

**Comment by beeman** [comment]
Thanks for fixing @jvandemo 👍

**Comment by jvandemo** [comment]
@beeman &mdash; Thank YOU Bram! 👍
