### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by axtho** [jvandemo/generator-angular2-library#230]
With the release of Angular v5 it would be great if this generator could also work with ng5. Currently there seem to be a few issues with dependencies: e.g. minimist (probably from run-sequence?).

**Comment by axtho** [comment]
here is one step towards that: https://github.com/filipesilva/angular-quickstart-lib/issues/61#issuecomment-341353735

**Comment by flauc** [comment]
It's a simple as doing this: 

`gulpfile.js`

```
gulp.task('ngc', function () {
    ngc([ '--project', `${tmpFolder}/tsconfig.es5.json` ]);
    return Promise.resolve()
});
```

**Comment by axtho** [comment]
I confirm this works. Thanks!

**Comment by abalad** [comment]
same here

**Comment by jvandemo** [comment]
@flauc &mdash; Thank you for sharing, I'm working on an Angular 5 update and will include the fix 👍

**Comment by flauc** [comment]
@jvandemo I'm happy to help, this is the best library generator out there 👍

**Comment by jvandemo** [comment]
v12.0.0 of the generator has been published with support for Angular 5 👍 

Special thanks to @flauc for sharing the solution for `ngc` 🏆
