### ISSUE TITLE
npm run lint not working

### ISSUE THREAD

**Issue by dgroh** [jvandemo/generator-angular2-library#235]
I just created a package from the scratch following the docs here and when running `npm run lint` I get the following error:

> Error at src/sample.component.spec.ts:7:1: Cannot find name 'describe'.
Error at src/sample.component.spec.ts:14:3: Cannot find name 'beforeEach'.
Error at src/sample.component.spec.ts:28:3: Cannot find name 'it'.
Error at src/sample.component.spec.ts:29:5: Cannot find name 'expect'.

Any idea how to fix this?

**Comment by laurent1** [comment]
In tsconfig.json, you need to add this to the compilerOptions:
`  "types": [
      "jasmine",
      "node"
    ],
    "typeRoots": [
      "node_modules/@types"
    ]
`

**Comment by dgroh** [comment]
didn't help and I also installed `@types/jasmine`

**Comment by dgroh** [comment]
adding `"types": ["jasmine"]` fixed the issue, just forgot about that
