### ISSUE TITLE
Consuming library exposing rxjs observables

### ISSUE THREAD

**Issue by gkaran** [jvandemo/generator-angular2-library#236]
I'm creating a library that will provide some core services used accross several projects. Each project exposes some functions that have `Observable` return type.

When I'm trying to consume the library (linked at the moment as it is still under development) in a project I face some issues when I try to chain anything from the returned observables.

Let me provide a small example:

#### Library service
```ts
@Injectable()
export class LibraryService {

  public foo(): Observable<number> {
    return Observable.from([1, 2, 3]);
  }
}
```

#### Consuming project 

import { Subscription } from 'rxjs/Subscription';
import 'rxjs/add/operator/take';

```ts
@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.css']
})
export class FooComponent {

  private sub: Subscription;

  constructor(private s: LibraryService) {
    this.sub = this.s
      .skip(1)
      .subscribe(() => {}, () => {}); 
  }

}
```

In the consuming component, I do get the following errors:

**For the subscription:** TS90010:Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.

**For the operator:** TS2339:Property 'skip' does not exist on type 'Observable<number>'.

If I add the import of the operator in the library then everything works great. But this is cumbersome as it is not a good idea to import all the operators that a consumer might need.

Has anyone created a library that does something similar? I'm trying to find out what I'm missing here. Any help is much appreciated.

**Comment by gkaran** [comment]
I found the solution to my problem. Due to the fact that I was linking the library because I was still developing it, I was missing the corresponding path for rxjs in my tsconfig.json.

Chaning the paths to the following resolved the problem:

```json
"paths": {
  "@angular/*": [
    "../node_modules/@angular/*"
  ],
  "rxjs/*": [
    "../node_modules/rxjs/*"
  ]
}
```

**Comment by jvandemo** [comment]
@gkaran &mdash; Thank you for sharing the solution, much appreciated 👍
