### ISSUE TITLE
Please support Angular  5

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [jvandemo/generator-angular2-library#238]
Please support Angular  5.

[16:02:56] Starting 'ngc'...
[16:02:56] 'ngc' errored after 1.59 ms
[16:02:56] TypeError: args.indexOf is not a function
    at module.exports (/build/brower/gitrepos/src/packages/@mycompany/ngrx/node_modules/minimist/index.js:44:14)

Change gulpfile.js to:

/**
 * 4. Run the Angular compiler, ngc, on the /.tmp folder. This will output all
 *    compiled modules to the /build folder.
 */
gulp.task('ngc', function () {
  return ngc(['-p', `${tmpFolder}/tsconfig.es5.json`], (error) => {
    if (error) {
      throw new Error('ngc compilation failed: ' + error);
    }
  });
});

**Comment by jvandemo** [comment]
I'm working on an Angular 5 update. Should be released later this weekend 👍

**Comment by jvandemo** [comment]
v12.0.0 of the generator has been published with support for Angular 5 👍
