### ISSUE TITLE
Error if I have more than one component in the library

### ISSUE THREAD

**Issue by igogra** [jvandemo/generator-angular2-library#239]
I'm trying to generate a library with more than one component but I'm not sure how to do it. With only one works but with more than one I get errors like "Module not found". Is there any example on how to have more than one component? Should I create one module for each component and import those modules in the index.ts?

**Comment by karuniko** [comment]
that's true for services as well, works for single service only
@jvandemo could you please provide examples how to extend the library by adding services, components, etc?

**Comment by broweratcognitecdotcom** [comment]
@igogra How you package your components is up to you. But I recommend that if you're creating a shared library, that you place each component into a submodule of the main module. That way, you can import and use the whole lib or just the lib containing the widget you need.

@karuniko & @igogra There are no issues with extending the generated library. Just study the sample service and module. Do what the generator did.

**Comment by xrobert35** [comment]
Your index.ts contain one module. 

In this module, like a normal angular module you can declare in the **declarations** more than components, those components need also to be exported in the **exports** section and you need also to export to the component file (to build in prod mode): 

```
import {MyComp1} from './my.component1';
import {MyComp2} from './my.component2';

export * from './my.component1';
export * from './my.component2';

@NgModule({
  declarations: [MyComp1, MyComp2],
  exports: [MyComp1, MyComp2]
```

For service this is the same things but you only need to put your service in the **providers** attribut and to export the file.

Like @broweratcognitecdotcom said it's better to declare submodules  (one fonctional component = 1 modules) to do this you can simply use the  **imports**  **exports**  attribut. Don't forget to export your submodule file 


```
import { SubModule} from './my.submodule';

export * from './my.submodule';

@NgModule({
 imports : [SubModule.forRoot()],
 exports: [SubModule]
```

The submodule must take care to declare/providers/export   service and component and to export their files.

**Comment by izifortune** [comment]
Thank you @broweratcognitecdotcom  and @xrobert35
