### ISSUE TITLE
Version mismatch between library package.json vs. project package.json

### ISSUE THREAD

**Issue by btgoodwin** [jvandemo/generator-angular2-library#248]
https://github.com/jvandemo/generator-angular2-library/blob/b1b64971dee1d3f407d8518d74bb7b9c61e8fb11/generators/app/templates/src/_package.json#L24

The distributed `package.json` template (above) is set to `^4.0.0` rather than `^5.0.0` as in the top-level `package.json`.  Perhaps it might be worth using something like `sync-json` as suggested in [this thread](https://github.com/jvandemo/generator-angular2-library/pull/222) for synchronizing the two package files?

**Comment by btgoodwin** [comment]
It looks like rxjs and zone are also not the same version as the top-level `package.json`.

**Comment by izifortune** [comment]
We sure need to have a look at the option of syncing the `package.json`. I've replied to you @btgoodwin  on the PR thread. Personally i've used another solution but involved some external libraries which i'm not sure if we should include them or not.

I'm using `standard-version` using a postbump script that will be invoked after it.

**Comment by btgoodwin** [comment]
@izifortune yes, I Just saw that, thank you.  I posted a link to my current configuration as well.  It's probably a bit heavy-handed, but it's working well for us so far ([link](https://github.com/jvandemo/generator-angular2-library/pull/222#issuecomment-357947525)).

**Comment by izifortune** [comment]
Have a PR #267

**Comment by jvandemo** [comment]
PR has been merged 👍 

@btgoodwin &mdash; Thank you for reporting.
@izifortune &mdash; Thank you for the fix 👍
