### ISSUE TITLE
Removing of typings

### ISSUE THREAD

**Issue by maku** [jvandemo/generator-angular2-library#25]
I think it would be a good idea to get rid of the usage of typings in favour of the more modern approach with node_modules/@types and e.g. a lib entry in tsconfig.json.

**Comment by jvandemo** [comment]
@maku &mdash; Would you be able to create a PR with the necessary changes? Thanks in advance! 👍

**Comment by gabwh** [comment]
I've created https://github.com/jvandemo/generator-angular2-library/pull/29.
I think this is what @maku was asking.

**Comment by jvandemo** [comment]
Generator now uses @types, thanks to @gabwh's efforts in #29. 👍
