### ISSUE TITLE
npm link src with angular 5

### ISSUE THREAD

**Issue by sgentile** [jvandemo/generator-angular2-library#252]
I have symlinks enabled:

```
"build": {
      "preserveSymlinks": true
    }
```
but when I try to run against npm link with src, I get this error:

ERROR in ./node_modules/mylibrary/index.ts
Module build failed: Error: /Users/sgentile/Workspaces/myproject/node_modules/mylibrary/index.ts is not part of the compilation output. Please check theother error messages for details.

Any ideas?

**Comment by anteAdamovic** [comment]
Why are you trying to link the `src` anyway, you're suppose to link the `dist` directory. Angular 5 has known issues with compilation so it often doesn't accept raw TS files from third party libraries. I've ran into this problem with my own library which is why I'm checking this one out and it works great, simply run `npm run build` and then switch to `dist` directory and run `npm link` there.

**Comment by sgentile** [comment]
For development so you don't have to recompile after every change.  What
you described is very time consuming and not very productive

Certainly before preparing for release we link to dist.

On Dec 30, 2017 3:41 AM, "Ante Adamovic" <notifications@github.com> wrote:

Why are you trying to link the src anyway, you're suppose to link the dist
directory. Angular 5 has known issues with compilation so it often doesn't
accept raw TS files from third party libraries. I've ran into this problem
with my own library which is why I'm checking this one out and it works
great, simply run npm run build and then switch to dist directory and run npm
link there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jvandemo/generator-angular2-library/issues/252#issuecomment-354534636>,
or mute the thread

**Comment by txinfo** [comment]
@sgentile Did you ever find a workaround for being able to do this the old 'link src' way again?

**Comment by izifortune** [comment]
@sgentile have you tried @txinfo suggestion?

**Comment by sgentile** [comment]
I'll check, we have held off moving to angular5 at this time until

**Comment by jdjuan** [comment]
@sgentile I'm closing this issue for now. Feel free to re-open if you deem necessary after upgrading

**Comment by jvandemo** [comment]
@izifortune, @jdjuan &mdash; Thank you for your follow-up 👍
