### ISSUE TITLE
npm run playground - problems with RxJs

### ISSUE THREAD

**Issue by TarasKovalenko** [jvandemo/generator-angular2-library#255]
I have created empty library following the official guideline.
After that trying to run ```npm run playground``` to check if it's work.
After automatically opening new browser window I have catch next exception:

![image](https://user-images.githubusercontent.com/2806803/34361677-f25127f6-ea74-11e7-86dd-aed65e30f5fc.png)

```
node -v: v9.2.1
npm -v: 5.6.0
```
Any idea how to resolve this issue?

**Comment by caroso1222** [comment]
I'm not getting the error with your repro steps. Did you try saving some file inside the `/src` folder? that should trigger a rebuild

**Comment by TarasKovalenko** [comment]
@caroso1222 
My steps:

```
1. npm install -g yo
2. npm install -g generator-angular2-library

3. mkdir angular-library-name
4. cd angular-library-name

5. yo angular2-library

6. npm run build

7. npm run playground
```

Can you please give me steps to the build a library?

**Comment by caroso1222** [comment]
I just tried those steps again. I'm not getting the RxJS error yet, but I do get this error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:16 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/.playground/index.js
  Loading .playground/index.js
    at fetch.js:37
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at zone.js:858
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at <anonymous>
```

After that, if I kill the process and run `npm run playground` again, it works. It's weird.

**Comment by caroso1222** [comment]
Might be a duplicate of: https://github.com/jvandemo/generator-angular2-library/issues/244

**Comment by jvandemo** [comment]
@izifortune &mdash; Would you be able to have a look at this, Fabrizio?

Thanks in advance!

**Comment by TarasKovalenko** [comment]
@jvandemo @caroso1222 Hey, any update on this issue?

**Comment by izifortune** [comment]
Sorry I had a quick look and didn't found anything will keep digging during
the weekend

**Comment by TarasKovalenko** [comment]
@izifortune Thank you for your feedback. Please update this issue if you catch something new.

**Comment by izifortune** [comment]
Hi @TarasKovalenko can you please try to pull this PR #274 and see if that's still an issue?

**Comment by TarasKovalenko** [comment]
@izifortune Hey, for now, all work perfect, thank you!

**Comment by jvandemo** [comment]
@TarasKovalenko &mdash; Thank you for the confirmation.

@izifortune &mdash; Thank you for the follow-up 🏆

**Comment by TeodorKolev** [comment]
Same here. Not fixed

**Comment by DesertFoxNV** [comment]
I found a poor workaround:
1. Run the command `npm run playground`
2. Copy the `index.js` and `index.js.map` from the `.playground/playground` directory to the `.playground` directory.
3. Refresh browser.

**Comment by jvandemo** [comment]
@DesertFoxNV &mdash; Thank you for sharing 👍
