### ISSUE TITLE
how to add a sass/css compiler with generator-angular2-library?

### ISSUE THREAD

**Issue by johanmaia** [jvandemo/generator-angular2-library#26]
I'm using your angular app to create a library of components.
I would like to develop some components with *.sass or *.scss files and compile them in css in the "dist" folder.
I imagine the best way should be adding this option on the command line "npm run tsc".
Is it already included ? 
Can I do it easily ?

**Comment by jvandemo** [comment]
@johanmaia &mdash; There is no official best practice yet (which will be available when Angular CLI supports the creation of libaries).

Meanwhile, you can have a look at how Angular Material is doing this: they use Gulp to compile the SCSS to CSS in the `dist` directory.

You can find the source code right here: https://github.com/angular/material2/blob/master/tools/gulp/tasks/components.ts

Hope that helps!

I will close the issue for now. Feel free to re-open if you feel it is needed. Thanks!
