### ISSUE TITLE
npm run build -> 'rollup:fesm' error

### ISSUE THREAD

**Issue by ahmeti** [jvandemo/generator-angular2-library#260]
I tried the "npm run build" command. But it does not work :(

NPM -v: 5.6.0
NODE -v: 8.9.4

Do you have any idea about this? Thanks.

## Results:

`npm run build

> ng-test-package@0.1.0 build /Users/ahmet/code/ng-test-package
> gulp build

[16:40:46] Using gulpfile ~/code/ng-test-package/gulpfile.js
[16:40:46] Starting 'clean:dist'...
[16:40:46] Starting 'clean:tmp'...
[16:40:46] Starting 'clean:build'...
[16:40:46] Starting 'compile'...
[16:40:46] Finished 'compile' after 2.43 ms
[16:40:46] Finished 'clean:dist' after 13 ms
[16:40:46] Starting 'copy:source'...
[16:40:46] Finished 'clean:tmp' after 20 ms
[16:40:46] Finished 'clean:build' after 21 ms
[16:40:46] Starting 'clean'...
[16:40:46] Finished 'clean' after 297 μs
[16:40:46] Starting 'build'...
[16:40:46] Finished 'build' after 6.08 μs
[16:40:46] Finished 'copy:source' after 64 ms
[16:40:46] Starting 'inline-resources'...
[16:40:46] Finished 'inline-resources' after 8.09 ms
[16:40:46] Starting 'ngc'...
[16:40:48] Finished 'ngc' after 1.8 s
[16:40:48] Starting 'rollup:fesm'...
Error at /Users/ahmet/code/ng-test-package/playground/index.ts:9:31: Cannot find module 'ng-test-package'.
Error at /Users/ahmet/code/ng-test-package/src/sample.component.spec.ts:7:1: Cannot find name 'describe'.
Error at /Users/ahmet/code/ng-test-package/src/sample.component.spec.ts:14:3: Cannot find name 'beforeEach'.
Error at /Users/ahmet/code/ng-test-package/src/sample.component.spec.ts:28:3: Cannot find name 'it'.
Error at /Users/ahmet/code/ng-test-package/src/sample.component.spec.ts:29:5: Cannot find name 'expect'.

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Could not resolve entry (/Users/ahmet/code/ng-test-package/build/index.js)
    at error (/Users/ahmet/code/ng-test-package/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:185:14)
    at resolveId.then.id (/Users/ahmet/code/ng-test-package/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:9551:6)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-test-package@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-test-package@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahmet/.npm/_logs/2018-01-12T13_40_50_210Z-debug.log`

**Comment by izifortune** [comment]
Hi @ahmeti can you please share your tsconfigs? it seems that you are including `spec` files during the build which seems quite strange

**Comment by ahmeti** [comment]
Hi @izifortune thank you for your answer. I think, I found the source of the fault.

Firstly I tried,
```
yo angular2-library
```

Then I answered the questions.

```
? Your full name: Ahmet Imamoglu
? Your email address: xxx@gmail.com
? Your library name (kebab-case) ng-test-package
? Git repository url https://github.com/xxx/ng-test-package
? Test framework jest
```

If you answer **"jest"** to the "Test Framework" question, there is an error.
If you answer **"karma + jasmine"** to the "Test Framework" question, there is **no** error.

### My tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "rootDir": "./src",
    "lib": [
      "es2015",
      "dom"
    ],
    "skipLibCheck": true,
    "types": []
  }
}
```
Thank you for your support again.

**Comment by izifortune** [comment]
HI @ahmeti  can you please try to add

```
"exclude": [
 "**/*.spec.ts"
]
```
inside the src/tsconfig.es5.json for the jest option? And see if it works?

**Comment by izifortune** [comment]
It seems its related to rollup. I'm digging into it

**Comment by moridianmess** [comment]
Not sure if this will help with your digging, but when I had this issue it was because of a missing dependency, in my case I hadn't installed @angular/forms

**Comment by izifortune** [comment]
Will be fixed with #267 it seems was related to old versions of @angular/cli and rollup

**Comment by izifortune** [comment]
Closing as #267 is merged

**Comment by jvandemo** [comment]
Thank you, @izifortune 👍

**Comment by ashgibson** [comment]
I've just done a fresh install of node, yo and this generator and am getting the error when running `npm run build`.

node -v v9.9.0
npm -v 5.6.0
