### ISSUE TITLE
add standardized GitHub labels 🗂

### ISSUE THREAD

**Issue by jdjuan** [jvandemo/generator-angular2-library#263]
Hey @izifortune ! I just noticed you recently added labels to the project. I wanted to suggest using:

https://github.com/yoshuawuyts/github-standard-labels

That way new-comers and contributors can quickly understand the status of our issues. In case you agreed, we would simply add some missing ones, and rename existing ones. 👍

**Comment by izifortune** [comment]
Hi @jdjuan I was using labels coming from the autocomplete here in github. That seems reasonable to add those labels I will have a look into it

**Comment by caroso1222** [comment]
+1 for the standard-labels

**Comment by jvandemo** [comment]
Labels have been added 👍 

@jdjuan, @izifortune, @caroso1222 Thank you so much for your help. Much appreciated! 🏆
