### ISSUE TITLE
How to pass configuration parameters for this library from inside consuming project

### ISSUE THREAD

**Issue by Basel78** [jvandemo/generator-angular2-library#268]
I have build few libraries using this template, which finds it very helpful.
What I need now is to use parameters or configuration file from the project that will consume my library, that are needed inside the library to function properly,
Think of like URL, or environment parameter, that the library will use to make calls or run certain actions.

how to implement such scenario!
Thanks

**Comment by kkozlowski89** [comment]
Hi,

here is code:

```
export const MODULE_CONFIG = new InjectionToken<any>('');


export class YourModule {
    static forRoot(config: any): ModuleWithProviders {
        return {
            ngModule: YourModule,
            providers: [
                { provide: MODULE_CONFIG, useValue: config },
                {
                    provide: YourService,
                    useFactory: createYourServiceFunc,
                    deps: [MODULE_CONFIG]
                },
            ]
        };
    }
}

export function createYourServiceFunc(config: any) {
    return new YourService(config.apiUrl);
}

```
and you can consume your library like that:

```
@NgModule({
    imports: [
        BrowserModule,
        YouModule.forRoot({
            apiUrl: 'http://localhost:10633/CreditRiskTool.Api/api/1.0/'
        }),
   ],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
class AppModule { }
```

**Comment by izifortune** [comment]
Thank @kkozlowski89 closing the issue as answered

**Comment by jvandemo** [comment]
@kkozlowski89 &mdash; Thank you for sharing 👍

**Comment by Basel78** [comment]
Hi @kkozlowski89 ,

Thank you for posting the solution here, it works for me in angular-cli, the issue now coming up again when I want to reuse the library in Angular-SPA aspnetcore 2.0 template, and the Error that occur is:
"Uncaught Error: Can't resolve all parameters for DocumentService: ([object Object], ?)."

do you think this approach still valid for Angular SPA?

**Comment by kkozlowski89** [comment]
Yes, is still valid (I use it).

Now you have problem with dependency incjection. Please check constructor in DocumentService and pelase comment each paramater and check which parameters cause problem.

Maybe it is not a problem with solution above, maybe other parameter cause problem?

**Comment by Basel78** [comment]
Hi @kkozlowski89 ,
It is actually still valid, and it turn to be the reason of this issue is due to use library in symlinks mode, by adding it to the project using npm link, and as you know angular-cli is allowing to use "ng serve --preservesymlinks" , where asponetcore 2.0 is handling the execute of this command in the background, which means it run only "ng serve" without --preservesymlinks, and I had to update the one line of code in "webpack.config.js" with "modules: [path.join(__dirname, "node_modules")] ".

Thank you for your advice and following up.
