### ISSUE TITLE
Electron integration support: with 3rd party non-ngx-library dependency 

### ISSUE THREAD

**Issue by johnking** [jvandemo/generator-angular2-library#273]
Hi there, 

I have built a simple library on top of `pdf.js` based on this seed library, everything works just fine with Browser.

but there are some issues to use it in Electron. 

First, I got an error: 

<img width="827" alt="screen shot 2018-01-26 at 20 09 38" src="https://user-images.githubusercontent.com/1787137/35466764-ef6c5dd0-02d4-11e8-9b30-3ac01a89363d.png">

After googling around, I tried a few workarounds, like the one below by adding following code into index.html, 

```
<script> var exports = {} </script>
```

it made the previous issue disappeared, but with new issue as below. 

<img width="908" alt="screen shot 2018-01-26 at 20 18 45" src="https://user-images.githubusercontent.com/1787137/35466885-3b711f94-02d6-11e8-8977-359dac8ca77b.png">

May someone give me any suggestions/hints how to tackle this issue?

thanks

**Comment by johnking** [comment]
I close this request because I found the errors were due to my usage of pdf.js.

**Comment by jvandemo** [comment]
@johnking &mdash; Thank you for the update 👍
