### ISSUE TITLE
Error: StaticInjectorError[SampleService-> HttpClient]

### ISSUE THREAD

**Issue by budara** [jvandemo/generator-angular2-library#293]
I am linking a test angular library created using the generator to a angular-cli project. But, just injecting httpClient to SampleService throw error saying StaticInjectorError(AppModule)[SampleService->HttpClient]: NullInjectorError: No provider for HttpClient! ....

when I searched for a solution, most of post says to use preserveSymLinks: true ; but that is not working for me.

If anyone has solution, please help.

**Comment by budara** [comment]
preserveSymLinks worked for me;

In .angular-cli.json file updating to:-
"defaults": {
    "styleExt": "css",
    "build": {
        "preserveSymlinks": true
    },
    "component": {}
  }

**Comment by jvandemo** [comment]
@budara &mdash; Thank you for the update 👍
