### ISSUE TITLE
AOT 

### ISSUE THREAD

**Issue by arat3091** [jvandemo/generator-angular2-library#30]
Will it create metadata.json also so that AOT compilation does not fail.

**Comment by jvandemo** [comment]
Yes, you can perform the following commands:

```bash
# Install dependencies
$ npm install @angular/compiler-cli typescript@next @angular/platform-server @angular/compiler

# Compile
$ ./node_modules/.bin/tsc -p path/to/project
```

This will generate a compiled version in the `dist` directory with `index.metadata.json`.

I will also update the generator to include a build script to automate this.

Thank you for your feedback! 👍

**Comment by jvandemo** [comment]
I have just released v5.1.0 which includes the necessary dependencies and an `npm run build` script.

I will close this issue for now. Feel free to re-open if you feel something is missing.

Thanks again for your feedback!

**Comment by gaetansenn** [comment]
Hi, I'm currently using your generator with ionic 3 but I have a problem with the AOT compilation when I'm doing the command : ionic cordova build ios --prod.

Here my error: Error: Error encountered resolving symbol values statically. Calling function 'MyModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in src/app/app.module.ts, resolving symbol AppModule in src/app/app.module.ts

I would like to know if it's possible to add the compilation with AOT support ? As i don't see the index.metadata.json.

Regards,

**Comment by gaetansenn** [comment]
My bad the metadata.json has been generated with the name n9-angular2-storage.metadata.json, so it's mean that the AOT compilation should working. Why I don't have this error during the compilation of the library but with ionic ?

Regards,

**Comment by jvandemo** [comment]
@gaetansenn &mdash; Awesome, thank you for keep us posted. Much appreciated! 👍
