### ISSUE TITLE
version 5 is not published to NPM

### ISSUE THREAD

**Issue by AdiDahan** [jvandemo/generator-angular2-library#31]
I was having issues with npm install on generated library related to 'postinstall typings'.
I saw there was a pull request related and noticed version 5 was released, but on npm the latest version is 4.
"4.0.0 is the latest of 18 releases"

I will install from GitHub, but I spent some time figuring our this was my issue - so if someone is having issues with post install typings that's the reason.

**Comment by jvandemo** [comment]
Thank you for reporting. v5.0.0 has now been published to NPM 👍
