### ISSUE TITLE
Error 404 / systemjs

### ISSUE THREAD

**Issue by MaunyM** [jvandemo/generator-angular2-library#32]
I try to add a generated library to Angular 2's hero projet.
[https://github.com/angular/quickstart](https://github.com/angular/quickstart)

When i run my server, (npm start) i've got an 404 error : 
`[1] 17.01.27 17:15:00 404 GET my-lib`

I try to add : 
`my-lib': 'npm:my-lib`
or 
`my-lib': 'npm:my-lib/dist`

to systemjs.config.js

**Comment by jvandemo** [comment]
There currently is no embedded build process yet to build a standalone bundle.

We are waiting for the official recommendations from the Angular team on the library package format (which should be available soon) before adding a generic build process to this generator.

Meanwhile, you can add your own build process to build the package format you need or import the library using TypeScript and bundle it in your application bundle using a bundler like Webpack.

I will close this issue until further notice from the Angular team but feel free to re-open if you have any additional questions. Thanks!
