### ISSUE TITLE
[proposal] Remove "2" from the generated Angular[2] <- library created names

### ISSUE THREAD

**Issue by MarkPieszak** [jvandemo/generator-angular2-library#33]
Since going forward Angular2 is just going to be called Angular, it might be best to make sure people call their libraries by that (`angular-libraryname`), or the other common shortcut `ngx-libraryname`.

http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html

Should we make some quick updates to the generator so we make sure people start going that route?
Maybe even just a *note* to let people know about new naming conventions?

Just trying to help! :)

**Comment by jvandemo** [comment]
@MarkPieszak &mdash; Great idea, I have prepared PR #35.

Before I merge the PR, do you feel anything else would need to be updated?

Thanks in advance!

**Comment by MarkPieszak** [comment]
So far so good, if anything else sticks out I'll make some PRs!
🥇 love this generator.

**Comment by jvandemo** [comment]
@MarkPieszak &mdash; Awesome, thank you for your help and kind feedback. Much appreciated! 👍
