### ISSUE TITLE
Update to `yeoman-generator@1.x`

### ISSUE THREAD

**Issue by SamVerschueren** [jvandemo/generator-angular2-library#37]
I noticed you are still using `yeoman-generator@0.22.0`. Nothing wrong with that, but not a long time ago, Yeoman released version 1.x of `yeoman-generator`.

An example of a generator using that is [generator-nm](https://github.com/sindresorhus/generator-nm/blob/master/app/index.js). Since that version, you can use a class instead of an object which usually gives cleaner code.

I'm open for doing a PR if you want. Just let me know.

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; A PR would be wonderful, thank you, Sam! 👍

**Comment by SamVerschueren** [comment]
Alright, I will when I find a little bit of time :).

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; Thank you, Sam, much appreciated!

**Comment by jvandemo** [comment]
Updated to Yeoman 1.x 👍
