### ISSUE TITLE
**Feature Request** file structure to match that created with angular-cli command ng new

### ISSUE THREAD

**Issue by BBaysinger** [jvandemo/generator-angular2-library#39]
It would be nice to see the file structure match that created with angular-cli command ng new. Or maybe just as an option.

**Comment by jvandemo** [comment]
@BBaysinger &mdash; Once Angular CLI supports generating a library, we will update the generator to use the same structure. Meanwhile, I will close this issue. Feel free to re-open it again when Angular CLI has been updated. Thanks for your input, much appreciated! 👍

**Comment by BBaysinger** [comment]
Thanks. Appreciate the work you've put into this!

**Comment by jvandemo** [comment]
@BBaysinger &mdash; Thank you, Bradley, much appreciated!
