### ISSUE TITLE
Getting error when TSC is run

### ISSUE THREAD

**Issue by jrgleason** [jvandemo/generator-angular2-library#41]
I am following the directions, however, when it runs tsc I see `node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.`. Is it using an older version of the type or something?

**Comment by jcortes** [comment]
I have the same error, any suggestions on this issue for now?, thanks

**Comment by jvandemo** [comment]
This seems to be related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569.

I will loosen the TypeScript version and deploy a new version. Thank you for letting us know! 👍

**Comment by jvandemo** [comment]
Fix has been pushed as v5.3.0.

@jrgleason, @jcortes Would be great if you could verify if it works.

Thanks again for reporting! 👍

**Comment by jrgleason** [comment]
reference the PR?
