### ISSUE TITLE
Should we still use forRoot?

### ISSUE THREAD

**Issue by jrgleason** [jvandemo/generator-angular2-library#42]
The index.ts that gets generated includes a `forRoot` function...

```
export class SampleModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SampleModule,
      providers: [SampleService]
    };
  }
}
```

These seem to have been deprecated in most libraries (off the top of my head D3 and AngularMaterial). Do we still want to have this be the template?

**Comment by jvandemo** [comment]
@jrgleason &mdash; It mainly depends on the library. If the library contains a provider that must be registered with the root injector, then the `forRoot()` function is needed.

It may help library authors if we add a comment in the `index.ts` file to illustrate this and prevent misunderstandings.

What do you think? Thank you for your feedback!

**Comment by jvandemo** [comment]
Let's keep it in there until we get official recommendations not to 👍
