### ISSUE TITLE
Remove @types/protractor

### ISSUE THREAD

**Issue by jrgleason** [jvandemo/generator-angular2-library#43]
Per my npm install...

`npm WARN deprecated @types/protractor@4.0.0: This is a stub types definition for Protractor (https://github.com/angular/protractor). Protractor provides its own type definitions, so you don't need @types/protractor installed!`

I can look into it later but it may involve some other upgrades too. Anyone know if the tsLint issues that prevent people from upgrading have been resolved?

**Comment by jvandemo** [comment]
@jrgleason &mdash; Thank you, `@types/protractor@4.0.0` has been removed in v5.5.0 and tslint and codelyzer have been updated to the latest versions.

Feel free to re-open this issue if you experience any other issues. Thanks again!
