### ISSUE TITLE
Change the pattern of exports

### ISSUE THREAD

**Issue by Bigous** [jvandemo/generator-angular2-library#5]
Hi @jvandemo ,
Recently I used your generator to create the ng2-highcharts library at npm. It's great! Very usefull.
Than, @NathanWalker pointed me to this discution angular/angular-cli#96 which I think is a very good patter to follow.

It would be nice to have this pattern implemented in this generator. What do you think?

**Comment by jvandemo** [comment]
@Bigous &mdash; The new pattern has been added today by @NathanWalker so it's in the generator now.

Thanks for your feedback and thanks to @NathanWalker for bringing it to this generator!
