### ISSUE TITLE
Dash-Case vs. CamelCase

### ISSUE THREAD

**Issue by bersling** [jvandemo/generator-angular2-library#50]
In the readme, you write

```
<h1>{{ title }}</h1>
<sampleComponent>
  This component is part of the shared library and will now work as expected.
</sampleComponent>
```

however, when I tried it out, I had to use

```
<h1>{{ title }}</h1>
<sample-component>
  This component is part of the shared library and will now work as expected.
</sample-component>
```

Is this an issue or just a misunderstanding of concepts from my side?

**Comment by caroso1222** [comment]
Yeah this is absolutely a typo in the README. You want to go ahead an open a PR for this?

**Comment by jvandemo** [comment]
Thank you, much appreciated. PR has been merged 👍
