### ISSUE TITLE
Solution wont works with html file template

### ISSUE THREAD

**Issue by gilbertowa** [jvandemo/generator-angular2-library#52]
I change sample componente to read HTML file template, but dist wont works. Given error 

> Unhandled Promise rejection: Failed to load sample.component.html

**Do you have any solve?**

Look the change:

`@Component({
 selector: 'sample-component',
templateUrl: './sample.component.html'
})
export class SampleComponent {}`

**Comment by gilbertowa** [comment]
Sorry same that #15

**Comment by jvandemo** [comment]
@gilbertowa &mdash; thank you, we are indeed waiting for official recommendations 👍
