### ISSUE TITLE
Error when using npm link into an angular-cli project

### ISSUE THREAD

**Issue by IckleChris** [jvandemo/generator-angular2-library#57]
Currently a freshly generated project causes the following error when using `npm link` to test the library within a local `angular-cli` project;

`ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /path/to/project/node_modules/library-name/node_modules/@angular/core/core.d.ts, resolving symbol SampleModule in /path/to/project/node_modules/library-name/index.ts, resolving symbol SampleModule in /path/to/project/node_modules/library-name/index.ts`

I've dealt with this same problem in a separate library component I have (that does not use this generator) and the solution was to move the `@angular/*` dependencies from `dependencies` to `peerDependencies` in `package.json` [(as here)](https://github.com/IckleChris/ic-datepicker/blob/master/package.json#L65) as it causes some bizarre errors (I believe in TypeScript). I don't know if this is something you want to deal with?

**Comment by jvandemo** [comment]
@IckleChris &mdash; Can you try importing `SampleModule.forRoot()` instead of `SampleModule` in your applications, as in:

```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    SampleModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Can you let me know if that helps? Thanks!

**Comment by IckleChris** [comment]
Same error I'm afraid - only thing I can do that fixes the issue is removing/renaming `node_modules/@angular`

**Comment by jvandemo** [comment]
@IckleChris &mdash; Renaming/removing works as well here as a workaround.

Feel free to let us know if you find a better way, while we search for a solution.

Thanks again!

**Comment by jvandemo** [comment]
@IckleChris &mdash; I have just released v8.1.0 with an updated build process and npm link guidelines, which should allow you to accomplish exactly this.

Feel free to try it out and report back. Thanks again for your feedback! 👍

**Comment by caroso1222** [comment]
For anyone who come across this issue again. This seems to be related to a TypeScript bug when using `npm link` or `yarn link`. Setting `paths` in the CLI project's `tsconfig.json` seems to solve this issue, instead of using `.forRoot()`.
This might help: https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771

**Comment by jvandemo** [comment]
@caroso1222 &mdash; Thank you, much appreciated! 👍
