### ISSUE TITLE
Adapting to the latest Angular Library Spec presented by Google

### ISSUE THREAD

**Issue by jdjuan** [jvandemo/generator-angular2-library#58]
@jvandemo in the latest ng-conf Jason Aden from Google presented an approach to building Angular Libraries using Angular Compiler (NGC) and Rollup. More information can be found [here](https://www.youtube.com/watch?v=unICbsPGFIA). This is the favored way to create Angular libraries according to Stephen Fluin from the Angular Core team.

So I opened this issue to know if you have considered refactoring this generator a little bit to better align with those practices which make libraries AOT ready.

If so, we could use this issue to document the changes that need to be addressed and how contributors should be able to help. What are your thoughts?

**Comment by caroso1222** [comment]
Thanks @jdjuan. This is so in point, I'm absolutely waiting for this.

**Comment by jvandemo** [comment]
Absolutely, yes. We've been waiting for the guidelines for a long time, so I'm looking forward to integrating them with this generator.

Feel free to start creating a list of required changes. I will have a look at Jason' talk later today as well. Thanks in advance! 👍

**Comment by jvandemo** [comment]
I have just released v8.1.0 with the latest specifications from the official Angular Package Format.

Check out #60 for more information if you are interested and feel free to leave feedback if you have a chance to try it out.

Thanks for all your suggestions and feedback! 👍
