### ISSUE TITLE
How would i use a generated library in plunkr

### ISSUE THREAD

**Issue by BioPhoton** [jvandemo/generator-angular2-library#59]
I'm not sure how i should use the generated lib in a plunkr.

When i try to load it like:   
`<script src="https://unpkg.com/my-generated-lib-on-npm@1.1.1/dist/index.js"></script>`  

i get a "Uncaught ReferenceError: exports is not defined"error...

Is there a demo for this?

**Comment by jvandemo** [comment]
From what I understand, the Angular team is trying to move away from UMD bundles.

The recommended way of consuming libraries is to import a Flat ES Module so the consuming application can perform AOT compilation and tree shaking. Unfortunately, that means libraries can not just be included using a script element.

However, if you still insist on using a UMD bundle, you should be able to use a tool like Rollup to produce one. Although that will not allow your consuming application to optimize and tree shake the library.

You can find more information in this [excellent talk by Jason Aden](https://www.youtube.com/watch?v=unICbsPGFIA).

I will close this issue for now. Feel free to re-open if needed. Thanks!
