### ISSUE TITLE
Problem finding angular2 module

### ISSUE THREAD

**Issue by renancunha** [jvandemo/generator-angular2-library#6]
Hello,
When I run npm install, during the tsc execution I get this error:

TS2307: Cannot find module 'angular2/angular2'

What is the cause of this?
Sorry for open an issue for this, but I don't found nothing that works.

Thanks,
Renan.

**Comment by jvandemo** [comment]
@renancunha &mdash; I have just released v0.3.1.

Can you try and see if all is ok now? Thanks!!

**Comment by jvandemo** [comment]
Received confirmation from @renancunha that everything is working now.
