### ISSUE TITLE
add /dist to .gitignore

### ISSUE THREAD

**Issue by caroso1222** [jvandemo/generator-angular2-library#61]
Was wondering whether or not `/dist` should be ignored. I've gone through material, ngbootstrap and Ionic, which I consider some of the most relevant ng libraries out there, and all of them add `/dist` to the gitignore. 

I don't mind opening a PR for this, just wanted to open an issue and discuss this first.

**Comment by jvandemo** [comment]
Good thinking. I have added `dist` to `.gitignore`. Thanks again for your input, Carlos! 👍
