### ISSUE TITLE
Remove *.js from .gitignore

### ISSUE THREAD

**Issue by caroso1222** [jvandemo/generator-angular2-library#63]
Having `*.js` files ignored in the generated .gitignored is keeping developers from adding  gulp/grunt or any other root `.js` files to their project git versioning.

I might be missing something here so I better ask: Is there any reason to ignore all root `.js` files in the .gitignore?

For reference: https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/gitignore#L6

**Comment by jvandemo** [comment]
Good thinking. I have released v8.2.1 with a fix 👍
