### ISSUE TITLE
Scoped package name and publishConfig not correct

### ISSUE THREAD

**Issue by joachimprinzbach** [jvandemo/generator-angular2-library#66]
Gday Jurgen,

thanks for this awesome generator! 

We do have two small things that are currently not working as expected: 
- the publishConfig property in the package.json gets removed

it is not in the generated package.json in the dist folder, we need it to be able to publish the library in our internal sonatype nexus npm registry
`{
  "publishConfig": {
    "registry": "http://url-to-nexus-npm/"
  }
}`

- scoped library names get replaced by kebab-case

we are currently using scopes for our libraries
`"name": "@project/submodule"`
In the generated package.json, the name gets transferred to kebabcase "project-submodule".
Would it be possible to leave it as it is defined in the package.json? 

Thanks and kind regards
Joachim

**Comment by joachimprinzbach** [comment]
I am an idiot :-D

I edited the root package.json instead of the one in the src folder.
Everything is working as expected :-)

**Comment by jvandemo** [comment]
@joachimprinzbach &mdash; It can indeed be a little confusing when working with multiple `package.json` files. Glad to hear you fixed it and thank you for updating this issue 👍
