### ISSUE TITLE
add --dry-run option to skip npm install

### ISSUE THREAD

**Issue by jdjuan** [jvandemo/generator-angular2-library#68]
At times it is very useful to just generate the codebase without installing the NPM modules (since it could take a lot of time). The angular CLI has this option available. 

Do you consider this feature useful for the project? If so, I could add a PR.

`--dry-run` (alias: `-d`) _default value: false_

**Comment by jvandemo** [comment]
@jdjuan Yes, please, great idea, thank you 👍

**Comment by caroso1222** [comment]
Cli uses dry-run to avoid creating files, I think. They expose a skip-install flag to avoid npm install.

**Comment by jvandemo** [comment]
+1 for `--skip-install`.

Thank you Juan and Carlos! 👍

**Comment by jvandemo** [comment]
👍  😄

**Comment by jvandemo** [comment]
@jdjuan &mdash; I will close this issue for now. Feel free to re-open if needed.

Thanks again for your help! 👍
