### ISSUE TITLE
Libraries depending on libraries and template inlining not working?

### ISSUE THREAD

**Issue by btgoodwin** [jvandemo/generator-angular2-library#69]
First off, thank you for the generator.  It has been pretty tough figuring out exactly what the Angular community is aiming for with project configuration of libraries vs. applications.

I created two libraries (call them A and B) using this generator and an application using the angular-cli.  Library A depends on B, and the library A has `templateUrl` specified in a number of components.  When the app is built (`npm run build`), the templates are not included.  Also, the library that depends on the other can't run through `npm run build`.  

I'm not sure exactly which errors are caused by what problems, so I'm just going to walk through this here to see if I can get my libraries working (they've been fine up until now, but I've been using tsc and not been worrying about AoT).

Taking a step back to just Library A, if I run `npm run prepublish`, nothing gets inlined.
For example, one of the components in A that has a `templateUrl` specified, the corresponding `js` still says `templateUrl: 'the.component.template.name.html'` -- it was never in-lined.

Not knowing if this is tied to running `npm run build`, I tried it, but I get the following error:

```
Error: ENOENT: no such file or directory, open '/projects/ui-development/library-a/dist/node_modules/library-b/src/shared/base.service.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at MetadataWriterHost.writeMetadata (/projects/ui-development/library-a/node_modules/@angular/tsc-wrapped/src/compiler_host.js:115:22)
    at MetadataWriterHost._this.writeFile (/projects/ui-development/library-a/node_modules/@angular/tsc-wrapped/src/compiler_host.js:92:23)
    at Object.writeFile (/projects/ui-development/library-a/node_modules/typescript/lib/typescript.js:64240:132)
    at Object.writeFile (/projects/ui-development/library-a/node_modules/typescript/lib/typescript.js:9020:14)
    at printSourceFileOrBundle (/projects/ui-development/library-a/node_modules/typescript/lib/typescript.js:61204:16)
    at emitSourceFileOrBundle (/projects/ui-development/library-a/node_modules/typescript/lib/typescript.js:61155:21)
    at Object.forEachEmittedFile (/projects/ui-development/library-a/node_modules/typescript/lib/typescript.js:8986:17)
Compilation failed
```

It seems to be trying to open library B's base service metadata file in `library-a/dist/node_modules/library-b/src/...` (vs. `library-a/node_modules/library-b/dist/src/...`).

As for my project setup,  this project's README suggests using `npm link`.  The libraries cannot be linked because there seem to be many closed (and unresolved) issues related to the angular-cli generating applications that ultimately emit obscure errors about makeDecorator not being statically analyzable, etc. ([here's one](https://github.com/angular/angular-cli/issues/4647)).   Therefore my only solution so far has been to make my package.json dependency for the libraries point to a file path relative to the application or library:

__Application's package.json__

```
"dependencies": {
    "library-a": "../library-a"
```

__Library A's package.json__
```
"dependencies": {
    "library-b": "../library-b"
}
```

In each case, I then use `npm install ...` to install/refresh changes up-stream to the application.

I apologize for the rather wide net of errors, but I've been at this all day trying to unpack all these little obscure error messages.  At this point I'm not sure what errors are related and which are not since all of my code runs through tsc just fine.

**Comment by btgoodwin** [comment]
Actually a quick update.  I must have _just_ missed the 9.0 release 2 days ago when I started trying to use this, so I did not get any of the things related to inlining templates.  Now the issue is when I try to build library A, which depends on B, I end up with `RangeError: Maximum call stack size exceeded`, so I'm now off trying to figure out how to correct that issue, which seems to not reference anything about my own code.

**Comment by jvandemo** [comment]
@btgoodwin &mdash; The automatic template inlining is indeed only supported as of v9.0.0.

If you get a `makeDecorator` error, make sure to `npm link` the `dist` directory, not the root directory of your library.

It's hard to figure out what is causing the `RangeError` without seeing the actual code. It would be great if you could keep us posted if you find out what is causing it.

Thanks in advance!

**Comment by btgoodwin** [comment]
@jvandemo Thanks for catching that (about the `dist` directory).  I misread the instructions.

I've restarted now with actually creating a bare library B and library A such that B depends on A.  I also de-conflicted the module names, components, etc. (so SampleModuleB, SampleComponentB, etc.).  For module B's SampleComponentB, I changed it from `template` to `templateUrl` and placed the contents into an html file under `./html/sample.component.html`:

```
@Component({
  selector: 'sample-component-b',
  templateUrl: `html/sample.component.html`
})
export class SampleComponentB {

  constructor() {
  }

}
```

I then linked A's `dist` into B as suggested.

When I run `npm run build` on library B, the output `dist/index.js` still shows `templateUrl: ...` as in the original source.  If I move that HTML file into the same directory as the component, I get the same result.  I've looked in each of the output files, and I don't see where the HTML ever was inlined.

The issue with call size exceeded is clearly something wrong with my real libraries, as these basic sample ones don't have the same issue.

Just in case this was an Angular-CLI issue, I linked B and A into my app and imported each of their modules.  The template for SampleComponentB still does not get inlined anywhere.

**Comment by jvandemo** [comment]
@btgoodwin &mdash; Okay, if I understand correctly, you have 2 libraries:

- Library A
- Library B

From the Library A directory you should:

- `$ npm run build` to generate `dist` directory for library A, which should inline styles and templates of library A in the bundle in its `dist` directory
- `$ npm link dist` to link the `dist` directory of library A

Then from the Library B directory, you should:

- `$ npm link library-a` (or whatever you named library A in its `src/package.json`
- `$ npm run build` to generate `dist` directory for library B, which should inline styles and templates of library B in the bundle in its `dist` directory

Also, for automatic inlining of templates and styles, you must have version 9.0.0 of this generator.

Can you let us know how that goes? Thanks! 👍

**Comment by btgoodwin** [comment]
Correct on all points.  Actually, I just figured out the problem.

On library-b, where I swapped the `template` for `templateUrl`, I accidentally left the backticks:

```
// Was:
template: `sample.component.html`

// Should have been this based on the inlineTemplate:79 in inline-resources.js
template: 'sample.component.html'
```

I discovered this when I tried to make library-a reproduce the same issue.  So in-lining does work as expected since I suppose people won't be putting their URLs in backticks. 😉 

Consequently though, should one be concerned with rollup's messages:

```
'library-a' is imported by build/index.js, but could not be resolved -- treating it as an external dependency
```

**Comment by caroso1222** [comment]
@btgoodwin that rollup message is nothing to be concerned about. If lib-b depends on lib-a then lib-a is an external dependency indeed. If you want to get rid of this message though, find the 'rollup' task in your gulpfile and add lib-a to the 'external' property of rollup.

**Comment by btgoodwin** [comment]
That's what I figured however in a previous version of our libraries, it was an indication that libraries were being "skipped" for the bundle.

Thanks everyone.  I'm still trying to figure out why my "real" library-b is throwing that stack error, but I'm convinced that's not an issue with your tooling. 

Many thanks for putting this together! 👍

**Comment by jvandemo** [comment]
Awesome, thank you @caroso1222 and @btgoodwin for the help and updates.

Much appreciated!

**Comment by btgoodwin** [comment]
@jvandemo @caroso1222 for the sake of closing the loop on my last two problems in case someone's google voyage drops them here:

`RangeError...` when produced by gulp ngc: This was because of a ModuleWithProviders pattern that worked fine back in 2.x with `Optional()` arguments configuring a service.  My setup was like the old `RouterModule`, using `OpaqueToken`.  Now you have to use `InjectionToken` which requires specifying a type.  Mine is a double string list (originally, specified as `Array<Array<string>>`).  That was my problem.  Switching to `string[][]` fixed it. :man_shrugging:

I then started getting `TypeError: Cannot read property 'module' of undefined` without any reference to my code.  That problem was related to the 2.x method of configuring submodule routes in the `RouterModule`.  In the past, to get that working where you navigate to components provided by child modules and routes, one had to export the child routes all the way out to the parent where `forRoot` would be used to configure the routes.  Now, it seems they have `forChild` and `loadChildren` working such that the parent sets its path to the child:

```
{ path: 'some-path', loadChildren: './some-child/module#SomeChildModule' }
```

Cheers :)

**Comment by jvandemo** [comment]
@btgoodwin &mdash; Awesome, thank you so much for the update. I am sure this will help many others in similar situations.

Much appreciated! 👍
