### ISSUE TITLE
Creating an angular2 library seed project

### ISSUE THREAD

**Issue by NathanWalker** [jvandemo/generator-angular2-library#7]
@jvandemo I wanted to get your thoughts on this...

I'm planning on creating an angular2 library seed project. The advantage to a seed project over a generator is you get the project tooling, build pipeline, testing support, and an out of box setup to demo the library. It also prepares the developer for publishing their library to `npm` with all the necessary `.gitignore` and `.npmignore` files to keep things tidy.

How does that sound? Does one already exist that you know of? Anything in particular that you think needs to be in there?

**Comment by NathanWalker** [comment]
Maybe it should have a dependency on this generator though and only provide the bare minimum basics... then the developer could use the generator to build out more files for their library?

**Comment by cthrax** [comment]
@NathanWalker I've been trying to workout the skeleton of the angular 2 version of angular-google-maps based on the wonderful angular2-seed project. I'd be very much interested in helping out with your seed project or any existing project you find (I have not found one as of yet).

**Comment by jvandemo** [comment]
@NathanWalker &mdash; Sounds like a great plan! I'm not aware of an existing seed project yet but maybe Olivier Combe knows more.

@Ocombe: would be great to hear your feedback on this. Thanks!

**Comment by ocombe** [comment]
Hey, no I don't know anything like this.
If you want we can host the project on preboot: https://github.com/preboot
I'd be happy to add you as a contributor, and to contribute to this as well.

**Comment by NathanWalker** [comment]
@ocombe Let's do that. I'll create the seed project this week on that org, thanks :+1:

**Comment by NathanWalker** [comment]
@cthrax I'll let you know how you could help this week!

**Comment by NathanWalker** [comment]
@jvandemo @ocombe Ok got it done here, hope you like it!
https://github.com/preboot/angular2-library-seed

**Comment by jvandemo** [comment]
@NathanWalker &mdash; Awesome, great work :+1: /cc @ocombe
