### ISSUE TITLE
ERROR in SampleModule is not an NgModule

### ISSUE THREAD

**Issue by sudhanshu-shekhar12** [jvandemo/generator-angular2-library#73]
Hi Team,

I followed the same approach and when i use ng build its giving me below error.

ERROR in SampleModule is not an NgModule

**Comment by jvandemo** [comment]
@sudhanshu-shekhar12 Can you provide a bit more details? What exactly did you do? What OS are you on? Thank you!

**Comment by jdjuan** [comment]
@sudhanshu-shekhar12 can you please provide the repo, that way we can help you out

**Comment by xxxtonixxx** [comment]
I have the same problem. I have done an out-of-the-box:
- `yo angular2-library`
- `yarn`
- `npm run build`
- `cd build && yarn link `
- I have tried with angular ^4.0.0 and 4.0.2 and nothing...
 
In an angular-cli project (fresh) I have done `yarn link test` and `ng serve --aot`

- [test.zip](https://github.com/jvandemo/generator-angular2-library/files/958337/test.zip)

I don't know what fails 😢

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!

**Comment by AdiDahan** [comment]
Sorry to reopen closed issue, but I'm experiencing the same issue.
After running 'start' on the consuming Angular 2 project, initial build will result in:
'ERROR in <MODULE_NAME> is not an NgModule'.

Recompile finishes successfully.
Angular 4, Windows 10.

Can totally live with it, but would be nice to get this fixed 😄

**Comment by jvandemo** [comment]
@AdiDahan &mdash; Is it possible to provide us with access to your repository?

Related thread in Angular CLI repository: https://github.com/angular/angular-cli/issues/3426.

**Comment by xxxtonixxx** [comment]
I have noticed it happens when `typings/types` prop of `package.json` does not point to an existing file.

For example:
```json
{
...
  "typings": "index.d.ts", // if this file does not exist, it will throw the `ERROR in ***Module is not an NgModule` error
...
}
```

**Comment by AdiDahan** [comment]
Unfortunately, this happens on a repo stored on GitHub Enterprise so I cannot provide access.
I've also checked the case with typings, they point to an existing file in my case.

If that helps, this happens on a "nested" library.

MyApplication -> LibraryA -> LibraryB

Both LibraryA and LibraryB are linked in MyApplication, and the error comes from LibraryB.

**Comment by digaus** [comment]
Did you manage to resolve this? Also getting the Error...

**Comment by AdiDahan** [comment]
I eventually regenerated a new project, and it was resolved.
I don't remember if I did had to take any additional steps.

Sorry, it's been a while since I resolved that 😞
