### ISSUE TITLE
Karma config not being generated 

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [jvandemo/generator-angular2-library#78]
On the generated files, there is no karma.config file being generated. I don't see it documented about the config options or am I missing something?

**Comment by jvandemo** [comment]
You are right. Currently there is no official consensus yet (see #1) on how to structure unit tests. E.g. one library author may put all tests in a `tests` directory while another library author may put tests in the `src` directory.

Until there is a consensus, you can run:

```bash
$ karma init
```

from the root of your library to create your own Karma configuration.

As soon as there are official guidelines, we will also add a default karma configuration to this generator.

I will close this issue for now, but feel free to re-open if you feel it is needed.

Thank you for your feedback!
