### ISSUE TITLE
Auto import in WebStorm not working

### ISSUE THREAD

**Issue by AdiDahan** [jvandemo/generator-angular2-library#80]
I'm trying to create two libraries, which one of the uses the second.
Everything is working fine, except one very annoying issue - I have to explicitly type the "import" statement for the other library.
WebStorm does not auto-complete it like it does for other libraries.

Am I the only one experiencing this issue ? is this a bug/configuration issue ?

Thanks

**Comment by AdiDahan** [comment]
I was finally able to resolve that by changing tsconfig to
{
...
"lib": [
"es2016",
"dom"
]
...
}

In case someone will find it useful.

**Comment by jvandemo** [comment]
@AdiDahan &mdash; Thank you for the update, much appreciated! 👍
