### ISSUE TITLE
Support for non angular-cli projects

### ISSUE THREAD

**Issue by EugeneSnihovsky** [jvandemo/generator-angular2-library#81]
Hi guys. First of all sorry for my English and thanks for your work. This repo is awesome!

I checked opened and closed issues but not found answer on my question. Is there a way to import generated module, for example, to [angular seed advanced](https://github.com/NathanWalker/angular-seed-advanced) project ?

I tried to create a module according your tutorial:
```
mkdir a2-test-module
cd a2-test-module
yo angular2-library
```
Then change exported module name to `SampleAngularModule` (to avoid name collisions) and:
```
npm run build
npm publish dist
```
The module was successfully [published](https://www.npmjs.com/package/a2-test-module)

Then in project created with ng cli
```
npm install a2-test-module
```
And import module to project
```typescript
import { SampleAngularModule } from 'a2-test-module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    SampleAngularModule,
    ///...
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```
Launch app with `ng serve` and it works like a charm

But when I do same things with [angular seed advanced](https://github.com/NathanWalker/angular-seed-advanced) project and launch server with `npm start` I have an error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:67 (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/a2-test-module.js
	Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/a2-test-module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1493632746292:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1493632746292:460:38) [<root>]
	Error loading http://localhost:5555/node_modules/a2-test-module.js as "a2-test-module" from http://localhost:5555/web.module.js Not expecting this error? Report it at https://github.com/NathanWalker/angular-seed-advanced/issues
```
You can reproduce it in my [forked](https://github.com/EugeneSnihovsky/angular-seed-advanced) repo.

Do I need to modify `tsconfg.json` or something else? Thanks in advance.

**Comment by jdjuan** [comment]
Hey @EugeneSnihovsky to me it seems more like a SystemJS issue. Have you tried adding your library [here](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/config/project.config.ts#L22) as stated in the docs? Probably it is required for it to work.

**Comment by EugeneSnihovsky** [comment]
@jdjuan Thanks for showing right direction.
I tried to add my library to `NPM_DEPENDENCIES` and other possible places, but it didn't help.
Now I understand that this is angular-seed-advanced problem and I created issue [there](https://github.com/NathanWalker/angular-seed-advanced/issues/418).
Thanks again for your help.

**Comment by jdjuan** [comment]
Thank you @EugeneSnihovsky for the update!

**Comment by jvandemo** [comment]
@EugeneSnihovsky &mdash; Thank you for the update!

@jdjuan &mdash; Thank you for jumping in!
