### ISSUE TITLE
Treated as external library message

### ISSUE THREAD

**Issue by ianqueue** [jvandemo/generator-angular2-library#82]
Apologies in advance if this is explained somewhere or I just haven't figure it out yet, but I love this generator... I was able to abstract sharable functionality from our angular-cli projects and add them as dependencies which is great!

The last piece to my puzzle is I noticed that my existing scss wasn't compiling correctly in the module which relies on a 3rd party library and it's component styling, so for example...

```css
/deep/ .mat-list-item-content {
    padding: 0 !important;
    height: auto !important;
}
```

works when part of the angular-cli bootstrapped application because it compiles it, but this module precompiles ( as it should ) for aot and by the time it gets to the application doesn't work as the styles have been inlined.

I am noticing I'm getting the message... 

```
[13:31:19] Starting 'rollup'...
'@covalent/core' is imported by build/index.js, but could not be resolved – treating it as an external dependency
```

What is the cause of the previous message?

Am I including this 3rd party library incorrectly, also libs like angular-material require you to create a themes.scss file for configuration etc. along with adding a platform.scss file to the assets key in .angular-cli.json

I've tried a number of things, but I'm missing the mark somewhere, curious if there are anything you know of that I can look at etc. that I may not have thought about, thanks!

**Comment by caroso1222** [comment]
That message is nothing to worry about. It just means that rollup will not bundle whatever is in your dependency but leave it as a ES2015 `import`. Webpack will handle this later on when compiling your project. If you're getting annoyed with this message, you can always add `@covalent/core` to the external dependencies on the rollup gulp task here https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/gulpfile.js#L70.

**Comment by ianqueue** [comment]
ah I see, but as for my other issue... i guess I just haven't figure out how to get the sass files from the 3rd party lib into the compilation mix, as you don't see any reason why I shouldn't be able to get the  `/deep/` module styling to override the 3rd party styling?

**Comment by ianqueue** [comment]
does the project support sass imports from 3rd party libs i guess is what I'm asking because when I tried it during a run build:watch it couldn't find the file to import.

**Comment by jvandemo** [comment]
@ianqueue &mdash; What exactly are your trying to accomplish?

Do you want to distribute scss files in your library so you can import them from within the scss files of your application? Thanks in advance!

**Comment by ianqueue** [comment]
@jvandemo - yeah i think that would definitely help, i was trying to figure out if my component library had angular-material as a dependency if there was a way to just compile and inline the styling so I wouldn't have to include a scss file in the consuming application ( built with angular-cli ), but i think thats not possible.  Obviously according to the docs you have to have a compilation with the parent application in order to do styling that targets child components ultimately ( ie. `/deep/` ).

I mainly just wanted to talk it over with someone to make sure I wasn't missing something.  Is there a way to output scss files for a given component?

Thanks!

**Comment by ianqueue** [comment]
Yeah... just looked through the gulp tasks... https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/tools/gulp/inline-resources.js#L100

simply replaces styleUrl with styles and inlines the styling, so later on anything like `/deep/` would get ignored.  So yes, if the answer is this tool doesn't output a sass file yet, thats cool maybe i can contribute, let me know...

**Comment by jvandemo** [comment]
@ianqueue &mdash; Thanks for the update. I think I don't completely understand the situation.

Would you be able to give an example with real files and styles? I'd love to help but at this point, it's not yet entirely clear (to me) what is happening.

Thanks again!

**Comment by ianqueue** [comment]
@jvandemo - yeah... it's really hard to stand up all of the things with 3rd party etc.  I will try, but you still didn't answer my easy question that you alluded to... can this build output a sass file?

Also I can't figure out how to pull in 3rd party library sass files for compilation.

**Comment by ianqueue** [comment]
Take a look at https://angular.io/docs/ts/latest/guide/component-styles.html and scroll down to /deep/ to understand the situation better.

**Comment by jvandemo** [comment]
@ianqueue &mdash; Would your request be resolved by #100? Thanks in advance!

**Comment by gryole** [comment]
I have th same message

> 'rxjs/Subject' is imported by build\header\shared\header.service.js, but could not be resolved – treating it as an external dependency

Adding 'rxjs' to external property does not remove warning. Is there any other way to solve this?

**Comment by jvandemo** [comment]
@gryole &mdash; You can learn more about the error here: https://rollupjs.org/#using-rollup-with-npm. 

It means your bundle will not include RxJS, which should be fine if the consuming application already imports it.

**Comment by jvandemo** [comment]
v10.2.0 now supports .scss imports. See #100 for more info. 👍
