### ISSUE TITLE
Should create and configure a second readme for the distribution of the library

### ISSUE THREAD

**Issue by dbfannin** [jvandemo/generator-angular2-library#83]
I wanted to first say thanks for this great tool!

I was wanting to get thoughts on adding a readme to the src directory when initializing a new library, and copying that file over to the dist directory on build (following the same pattern as the package.json). I'm currently doing this as a manual process after I build, and it would be nice to have it automated.

**Comment by jvandemo** [comment]
@dbfannin &mdash; I think that is a great idea 👍 

Are you interested in creating a PR for this? Thanks in advance!

**Comment by dbfannin** [comment]
Sure I can do that!

**Comment by dbfannin** [comment]
Do you think the route should be to just copy the root readme to the dist directory, or adding a second README to the templates?

**Comment by jdjuan** [comment]
To keep it simple, I would just leave one. It would be a responsibility of the user to create two sections within it: One for development and another one for usage! 🤓

BTW, @dbfannin thanks for taking thing one! 👍

**Comment by jvandemo** [comment]
@dbfannin &mdash; The `generators/app/templates/README.MD` file should do. It's already being generated in the root of the generated code. Thanks in advance!

**Comment by jvandemo** [comment]
Implemented in #85 and released as v10.1.0 👍
