### ISSUE TITLE
using gulp-inline-ng2-template aside from inline-resources

### ISSUE THREAD

**Issue by aelbore** [jvandemo/generator-angular2-library#87]
you can use existing library `gulp-inline-ng2-template`

Heres the code;

```javascript
const sass = require('node-sass');
const inlineNg2Template = require('gulp-inline-ng2-template');

const styleProcessor = (stylePath, ext, styleFile, callback) => {
  if (ext[0] === '.scss') {
    let sassObj = sass.renderSync({ file: stylePath });
    if (sassObj && sassObj['css']){
      styleFile = sassObj.css.toString('utf8');
    }
  }
  return callback(null, styleFile);  
};

const OPTIONS = {
  base: 'src', 
  useRelativePaths: true,
  styleProcessor: styleProcessor
}; 

const ng2InlineTemplate = () => {
  return inlineNg2Template(OPTIONS);
};

exports.ng2InlineTemplate = ng2InlineTemplate;
```

**Comment by jdjuan** [comment]
Thanks for you input @aelbore ! 🎉 

Can you tell the advantages of using gulp-inline-ng2 over the [our current implementation](https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/tools/gulp/inline-resources.js)? 🤔

**Comment by aelbore** [comment]
https://github.com/ludohenin/gulp-inline-ng2-template
there are some added flexibility or other options,  you can create your own implementation for style processor, if you want to minify or uglify your css. your implementation is straight forward. it works as well ^^

**Comment by jvandemo** [comment]
@aelbore &mdash; Thank you for the suggestion, much appreciated.

I suggest we wait to change the current behavior for now (unless there is an urgent reason) until Angular CLI comes with library generation.

We can then see how the Angular CLI team handles this and adjust accordingly if needed.

I will close this issue for now, but feel free to re-open or add comments if needed.

Thanks again for your input! 👍
