### ISSUE TITLE
Installing from git repo

### ISSUE THREAD

**Issue by yanqui92** [jvandemo/generator-angular2-library#88]
Hi!

I've followed the readme file to the end and I wanted to know how to install the library from a git repo.

**Comment by jvandemo** [comment]
@yanqui92 &mdash; What are you trying to accomplish?

Do you want to install your library without publishing your library to NPM? Thanks!

**Comment by yanqui92** [comment]
@jvandemo Exaclty! That's what I want

**Comment by caroso1222** [comment]
@yanqui92 then, what about if you create your library and then http://stackoverflow.com/a/17509764

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!

**Comment by chriszrc** [comment]
Hi, 

Yes, installing from git works just fine, but in this case, the folder that we need is dist, right? And dist is gitignored. If you push the whole project to a repo, the root package.json gets picked up, not the one from dist

**Comment by kirakishin** [comment]
+1
Yes i think, but i have the same problem. how we do that ?
may the solution is to publish not on npm, but on another repo (just the dist dir), then import it into our project ?

anything ?

**Comment by chriszrc** [comment]
Ok, there is a pretty easy way to handle this that I found. You can use git submodules. You create a separate repo for the library (the dist folder), and you can make it a submodule of the parent repository. But this way, when you npm install it from git, npm just see's the nice dist directory. 

This is working for me. I had to update the gulp script a bit to not delete the .git file that gets created, but the main configuration for the submodule is actually store in the parent, so even if it does get blown away, it's easy to get back-

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by bloigge** [comment]
@chriszrc I am facing the same problem. could you explain a bit in detail how you modified your gulp script. Are you creating the separate repo for the dist folder by hand for each new angular lib or do you have an automatism for that?
