### ISSUE TITLE
root directory is expected to contain all source files

### ISSUE THREAD

**Issue by islam-shaheen** [jvandemo/generator-angular2-library#90]
Hi,
Can I import my components and services in the index.ts from other folder, i get this error:
root directory is expected to contain all source files.
so I have to but all of the files inside the root directory??

Thanks!

**Comment by jdjuan** [comment]
Hi @islam-shaheen ! Thanks for opening this issue 💪 

It is not quite clear how the error happened to you: Can you please provide:

-  A repo where we can reproduce the problem
-  Your environment setup: OS, node version, version of this generator
- A more detailed, step-by-step process on how to reproduce your problem

Thanks in advance 👍

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!
