### ISSUE TITLE
Publish library to BitBucket and have it return only dist.

### ISSUE THREAD

**Issue by ivanstefan17** [jvandemo/generator-angular2-library#93]
@jvandemo Hey there!
I have the following scenario. I have 2 projects that both requiere a set of common components. I want to move those components into a library hosted in a private Bitbucket repository. 

How can i handle the build of the library in this scenario? Is it possible to install the dependency as is, with TS files and run the build afterwards or is there another, better way?

I've seen that on Github for example, all repositories have the TS files and after installing them in your project they come already compiled.

I hope is ok i opened a issue for this question.

**Comment by jvandemo** [comment]
@ivanstefan17 &mdash; Yes, that should work.

During development, you can link the `src` directory as outlined here:
https://github.com/jvandemo/generator-angular2-library#how-can-i-avoid-recompilation-during-development.

From the consuming application (e.g. application generated by Angular CLI), you will then have to import the Angular module from the `src` directory, which should cause the build process of the application to include the code in the output bundle.

Feel free to let us know how it goes and re-open this issue if needed 👍
