### ISSUE TITLE
How to add my custom .d.ts file to library?

### ISSUE THREAD

**Issue by yuriykuzin** [jvandemo/generator-angular2-library#94]
Hi,

I've created angular library. Then I want to add files with my custom types and place them into src/types folder, but compiler doesn't see them.

I've tried to use different paths in types, typeRoots in tsconfig.es5.json, but no luck yet.

Created a simple repo reproducing the problem: https://github.com/yuriykuzin/ng2-sample-library

Also created a question on stackoverflow:
http://stackoverflow.com/questions/44026110/how-to-add-my-custom-d-ts-file-to-my-angular-library

Any help is much appreciated. Thanks in advance!

**Comment by jvandemo** [comment]
The compiler uses `src/index.ts` as the main entry point to figure out which files to compile.

If your types are not imported in one of your project files, you will have to add the following line to `src/index.ts` to tell the compiler to include the types:

```typescript
import './types/sample-type';
```

This should result in `dist/types/sample-type.d.ts` being generated and referenced in `dist/index.d.ts`.

Can you please let us know if that works for you? Thanks!

**Comment by yuriykuzin** [comment]
Thanks @jvandemo for your answer! Though I'm still getting errors. I tried even to add 'export' to type declaration:

`export type SampleType = {
  test: string
};`

And the error is:

> Error at /Users/yuriy/studytube/sample-library/.tmp/sample.service.ts:6:22: Cannot find name 'SampleType'.

I've updated the repo.

Is there a way to avoid importing file with type declaration into each service/component/directive that uses it?

Also I'd like to use these types while consuming the library in other projects.

**Comment by jvandemo** [comment]
@yuriykuzin I just had a look at your repository. You need to do 3 things:

1. rename `src/types/sample-type.d.ts` to `src/types/sample-type.ts`
2. import `SampleType` in `SampleService` by adding a line `import { SampleType } from './types/sample-type';` in `src/sample.service.ts`. You must explicitly import `SampleType` in each file that references `SampleType`.
3. in `gulpfile.js`, add `allowRealFiles: true` to the `rollup:fesm` task option to support subdirectories in the `src` directory (you don't have to do this if you are using v10.2.1 or later of this generator). See https://github.com/jvandemo/generator-angular2-library/blob/master/generators/app/templates/gulpfile.js#L81 for an example.

Once you make those changes, your library will compile 👍 

Can you let us know if it works? Thanks!

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thanks!
