### ISSUE TITLE
Create a module for each Component

### ISSUE THREAD

**Issue by abalad** [jvandemo/generator-angular2-library#95]
I want to create a module for each component, so I can import it into my Application separately. Anyone have any idea how to do it?

**Comment by vinayakpatil** [comment]
+1

**Comment by jvandemo** [comment]
You can have a look at how the Angular Material library is structured right here:
https://github.com/angular/material2/blob/master/src/lib/module.ts

It exports multiple modules, which can then be imported selectively by the consuming application 👍

**Comment by pratikthecook** [comment]
i did the exact thing but couldnt get it running, i get the following error in my app 
`Module not found: Error: Can't resolve 'sample-library/maps/sample.maps.module'`

**Comment by abalad** [comment]
When importing the submodule into the application it is generating the following error in the Angular application.

`ERROR in Error: [module] is not an NgModule
`
And the import was from a simple module I created just to test this. With the new versions of Angular + AngularCLI + Your Generator

**Comment by deepthan** [comment]
hi @abalad @pratikthecook  ,Can you tell me what should i do? I tried but failed.
