### ISSUE TITLE
gulpfile dynamic parameters not being set correctly

### ISSUE THREAD

**Issue by dbfannin** [jvandemo/generator-angular2-library#98]
After updated to latest, the gulpfile is not being generated correctly.

```
      moduleName: '<%= props.libraryName.original %>',

      // See https://github.com/rollup/rollup/wiki/JavaScript-API#globals
      globals: {
        typescript: 'ts'
      }

    }))
    .pipe(rename('<%= props.libraryName.kebabCase %>.umd.js'))
```

this is creating a dist/<%= props.libraryName.kebabCase %>.umd.js file

**Comment by jvandemo** [comment]
I am not seeing this issue here (on Mac) and haven't been able to reproduce this.

@dbfannin &mdash; What version of the generator are you on? Have you tried reinstalling the generator yet?

Is anyone else experiencing this? Thanks!

**Comment by dbfannin** [comment]
That's very odd. I uninstalled and reinstalled and now it works like a charm. Same version number (generator-angular2-library@10.1.0). Not sure what was going on there. Closing this issue out.

**Comment by jvandemo** [comment]
@dbfannin &mdash; Thanks for the update! 👍
